window.GUIDE_DATA = {
  "app": {
    "title": "Salamanca Guide",
    "tagline": "Google Maps-ek oinak gidatzen ditu. PWAk begirada.",
    "defaultRoute": "dia2_goiza"
  },
  "routes": [
    {
      "slug": "dia1",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Lehen arratsaldea: hotelatik Fonsecaraino",
      "subtitle": "Kafea, harri urreztatua eta lehen orientazioa presarik gabe",
      "duration": "01:45",
      "summary": "Kongresuko harrerara iritsi aurretik, hiria lasai irakurtzen hasteko ibilbidea.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Colegio Arzobispo Fonseca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9652569,-5.6701508&travelmode=walking&waypoints=40.9653616,-5.6636406|40.9650282,-5.6640558|40.9629585,-5.6656516|40.961442,-5.667218|40.96445,-5.66859",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Irteera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Hiri garaikidetik alde zaharrerako trantsizio lasaia.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Ez gastatu lehen argazkia hemen; gorde lehen benetako koadroa erdigunerako.",
          "hidden_detail": "Hall88 ingurua muga atsegina da Salamanca egunerokoaren eta monumentalenaren artean.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Irteera: Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Lasai hasi. Gaur arratsaldean ez dugu “Salamanca egin” nahi: hiria irakurtzen ikasi besterik ez dugu egingo. Unibertsitate-auzo moderno batetik abiatu, erdiguneko harri urrezturantz joan eta harrera hasten den leku berean amaituko dugu.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu nola aldatzen den hiria alde zaharrera hurbiltzean: etorbideak estutu egiten dira, trafikoa gutxitzen da eta hareharria fatxadetan nagusitzen hasten da.</p>\n<h4>Historia</h4>\n<p>Hotela Miguel de Unamuno campusaren ondoan dago, autobus-geltokiaren aurrean. Eguneroko Salamanca eta Salamanca monumentala bereizten dituen muga ona da.</p>\n<h4>Bitxikeria</h4>\n<p>Villamayorreko harria ia krema kolorekoa dirudi egunez, baina albo-argiarekin ezti kolorekoa bihurtzen da. Kolore-aldaketa hori izango da paseoaren hari bisuala.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez da beharrezkoa hotela fotografiatzea. Gorde lehen irudia Plaza Mayor agertzen denerako: kontrasteak hobeto kontatuko du iritsiera.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Peña de Francia kaletik eta jarraitu erdigunerantz. Lehen helburua Café Novelty da, hogei minutu ingurura. Gurutza itzazu etorbideak seinaleztatutako pasabideetatik.</p>",
          "script_path": "../content/eu/dia1/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia1/parada01.mp4",
          "video_exists": true
        },
        {
          "id": 2,
          "time_rel": "00:24",
          "title": "Café Novelty",
          "short": "Kafea",
          "lat": 40.9653616,
          "lon": -5.6636406,
          "blurb": "Lehen atsedenaldiak paseoari erritmo egokia ematen dio.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Arkupeen azpitik, diagonalean, plazaren lehen markoa hartu.",
          "hidden_detail": "Kafetegiaren memoria literarioak plazaren ikuspegia baino gehiago ematen du.",
          "image": "../public/images/cafe-novelty.jpg",
          "script_html": "<h3>02 · Café Novelty</h3>\n<h4>Sarrera</h4>\n<p>Atsedenaldira une egokian iritsi zara, eta hori zen asmoa. Sartu Noveltyn 17:23 eta 17:25 artean, eta gorde hogei minutu inguru kafearentzat.</p>\n<h4>Zer begiratu</h4>\n<p>Bilatu hizketarako kafetegi-giroa, ez bakarrik Plazaren ikuspegia. Barruan Gonzalo Torrente Ballesterren eskultura dago, beste bezero bat balitz bezala eserita.</p>\n<h4>Historia</h4>\n<p>Novelty 1905ean ireki zuten, eta Salamancako kafetegirik zaharrena dela aldarrikatzen du. Haren mahaietatik hiriko bizitza kulturalaren zati handi bat igaro zen. Egungo lokalak memoria hori gordetzen du, denborarekin aldatu bada ere.</p>\n<h4>Bitxikeria</h4>\n<p>Torrente Ballesterrek hiri imajinarioei buruz idatzi zuen, baina hemen kafetegiko bizilagun iraunkor bihurtu zen. Tokirik badago, haren ondoan esertzea da geldialdi honetako erritu txikia.</p>\n<h4>Non egin argazkia</h4>\n<p>Egin barruko argazki bat eskulturarantz, beste bezeroei trabarik egin gabe. Kanpoan, jarri arkupeen azpian eta atera Plazaren argazkia diagonalean, arkuekin marko gisa. Gutxi gorabeherako orientazioa: ekialde-ipar-ekialdea.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Noveltytik Plaza Mayorreko erdialderantz. Hurrengo geldialdia minutu bat baino gutxiagora dago: ez hasi oraindik presaka; lehenik begiratu espazio osoa.</p>",
          "script_path": "../content/eu/dia1/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9653616,-5.6636406&travelmode=walking",
          "video_url": "../public/media/dia1/parada02.mp4",
          "video_exists": true
        },
        {
          "id": 3,
          "time_rel": "00:45",
          "title": "Plaza Mayor",
          "short": "Plaza",
          "lat": 40.9650282,
          "lon": -5.6640558,
          "blurb": "Ez helmuga gisa, sarrera handi gisa irakurtzeko plaza.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Erdialdean gelditu eta udaletxerantz zuzendu marko zabala egiteko.",
          "hidden_detail": "Laukia oso orekatua da, baina ez da guztiz simetrikoa.",
          "image": "../public/images/plaza-mayor.jpg",
          "script_html": "<h3>03 · Plaza Mayor</h3>\n<h4>Sarrera</h4>\n<p>Oraingoan Plaza Mayor ez da eguneko amaiera handia, sarrerako atea baizik. Gelditu minutu batzuk bakarrik: bihar beste argi eta beste erritmo batekin itzul zaitezke.</p>\n<h4>Zer begiratu</h4>\n<p>Jarri gutxi gorabehera erdian eta egin bira poliki. Plaza erabat erregularra dirudi, baina pabiloi bakoitzak bere eginkizuna du eta Udaletxeko kanpai-hormak horizontala hausten du.</p>\n<h4>Historia</h4>\n<p>Plaza barrokoa XVIII. mendean eraiki zen. Alberto de Churriguerak abiatu zuen proiektua, eta Andrés García de Quiñonesek osatu zuen multzoaren zati handi bat. Arkuetako medailoiek pertsonaien galeria bihurtzen dute arkupeetako ibilaldia.</p>\n<h4>Bitxikeria</h4>\n<p>Zenbatu aldeak begiradaz: karratu perfektu baten inpresioa ematen du, oinplano erreala hala ez izan arren. Arkitekturak erritmoaren eta errepikapenaren bidez zuzentzen du gure pertzepzioa.</p>\n<h4>Non egin argazkia</h4>\n<p>Erdigunetik, enkoadratu Udaletxea bertikalean; argazki lasaiago baterako, erabili arkupeetako arkuetako bat marko gisa. Ordu honetan argia gogorra izan daiteke: neurtu harrirako eta utzi zerua pixka bat argiago.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten plazatik hego-mendebaldeko irteeratik eta hartu Rúa Mayor. Bost minutu inguruan aurrez aurre agertuko dira Casa de las Conchas eta Clerecía.</p>",
          "script_path": "../content/eu/dia1/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9650282,-5.6640558&travelmode=walking",
          "video_url": "../public/media/dia1/parada03.mp4",
          "video_exists": true
        },
        {
          "id": 4,
          "time_rel": "00:57",
          "title": "Casa de las Conchas",
          "short": "Maskorrak",
          "lat": 40.9629585,
          "lon": -5.6656516,
          "blurb": "Fatxada bakarra eta Clerecíarekin duen elkarrizketa bisuala.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Clerecíaren aldetik, diagonalean, maskorren erritmoa hobeto ikusten da.",
          "hidden_detail": "Fatxada osoa ez da apaindura hutsa; botere sinbolikoaren erakusketa ere bada.",
          "image": "../public/images/casa-conchas.jpg",
          "script_html": "<h3>04 · Casa de las Conchas</h3>\n<h4>Sarrera</h4>\n<p>Hemen Salamancak liburu eta igarkizun izatera jokatzen du. Ez da barrura sartu behar: fatxadak berak kontatzen du leinuen, sinboloen eta prestigioaren historia.</p>\n<h4>Zer begiratu</h4>\n<p>Ez begiratu maskorrei bakarrik. Erreparatu leihoetako saretei, ateari eta aurrez aurre dauden Clerecíako dorreekin duen elkarrizketari. Espazioa estua da eta gora begiratzera behartzen du.</p>\n<h4>Historia</h4>\n<p>Jauregia XV. mendearen amaiera eta XVI.aren hasiera artean eraiki zuten Rodrigo Arias Maldonadorentzat. Maskorrak Santiago Ordenarekin lotzen dira, baina baita Pimentel familiaren ikurrarekin ere.</p>\n<h4>Bitxikeria</h4>\n<p>Kondairak dio maskorretako batek altxor bat ezkutatzen duela. Istorio ezin hobea da fatxada errepikakor baterako: dena berdina dirudienean, salbuespena bilatzen hasten gara.</p>\n<h4>Non egin argazkia</h4>\n<p>Gurutzatu Clerecíarantz eta erabili angelu zabal samarra. Maskorren erritmoa harrapatzeko, atera argazkia diagonalean fatxadaren iparraldeko muturretik. Orientazioa: mendebalde-hego-mendebaldea.</p>\n<h4>Nola jarraitu</h4>\n<p>Jarraitu Libreros kaletik eta biratu Patio de Escuelaserantz. Lau minutu inguruko bidea da oinez. Han bilatu Unibertsitatearen fatxada historikoa eta Fray Luis de Leónen estatua.</p>",
          "script_path": "../content/eu/dia1/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9629585,-5.6656516&travelmode=walking",
          "video_url": "../public/media/dia1/parada04.mp4",
          "video_exists": true
        },
        {
          "id": 5,
          "time_rel": "01:10",
          "title": "Unibertsitatea eta Patio de Escuelas",
          "short": "Unibertsitatea",
          "lat": 40.961442,
          "lon": -5.667218,
          "blurb": "Ikur handiak lehen begiratuan baino lasaiago irakurtzeko tokia.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Fray Luis lehen planoan utzi eta fatxada pixka bat alboratuta hartu.",
          "hidden_detail": "Jende gehiena igelaren bila hasten da eta eskulturaren kontakizun osoa galtzen du.",
          "image": "../public/images/universidad.jpg",
          "script_html": "<h3>05 · Unibertsitatea, Patio de Escuelas</h3>\n<h4>Sarrera</h4>\n<p>Patio hau eszenatoki txiki bat da. Jarri Fray Luis de León ondoan eta utzi estatuak nora begiratu esaten: fatxada ia harrizko orrialde bat da.</p>\n<h4>Zer begiratu</h4>\n<p>Igo begirada fatxadan behetik gora. Lehenik Errege Katolikoak, gero armarrien eta medailoien eremua, eta azkenik zatirik sinbolikoena. Ez bihurtu igela bilaketa urduri batean; multzoak jokoak baino gehiago balio du.</p>\n<h4>Historia</h4>\n<p>Salamancako Unibertsitatearen jatorria 1218ra doa. Fatxada plateresko ospetsua geroagokoa da, XVI. mendearen hasierakoa, eta boterea, ezagutza eta monarkia programa bisual beraren zati gisa aurkezten ditu.</p>\n<h4>Bitxikeria</h4>\n<p>Igela garezur baten gainean dago. Ikasleen tradizioak zorte akademikoa agintzen dio aurkitzen duenari, baina agian zentzuzkoena beste ikasgai bat da: arreta handiz begiratzeak beti laguntzen du azterketa batean.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri Fray Luisen atzean edo pixka bat albo batean haren silueta eta fatxada batera sartzeko. Orientazioa: mendebaldea. Erliebeetarako, erabili zooma eta saihestu mugikorra gehiegi makurtzea.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Patio de Escuelasetik Compañía kalerantz eta egin aurrera ipar-mendebaldera. Ibilbideak Monterrey jauregira eramango zaitu hamar minutu inguruan; Fonsecaren aurreko argazki-geldialdi laburra da.</p>",
          "script_path": "../content/eu/dia1/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.961442,-5.667218&travelmode=walking",
          "video_url": "../public/media/dia1/parada05.mp4",
          "video_exists": true
        },
        {
          "id": 6,
          "time_rel": "01:28",
          "title": "Palacio de Monterrey",
          "short": "Monterrey",
          "lat": 40.96445,
          "lon": -5.66859,
          "blurb": "Geldialdi labur baina oso fotogenikoa.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Hobe diagonalean, dorreak eta gailurreria batera sartzeko.",
          "hidden_detail": "Eraikin amaitu gabe batek estilo oso baten iruditeria markatu zuen.",
          "image": "../public/images/monterrey.jpg",
          "script_html": "<h3>06 · Monterrey jauregia</h3>\n<h4>Sarrera</h4>\n<p>Hau bost minutuko etenaldia da, ez bisita osoa. Jauregiak unibertsitate-gunearen eta Fonsecaren arteko giltza-lana egiten du.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu zeruaren kontra moztutako gailurreria, dorreak eta tximiniak. Goiko aldeak hainbesteko nortasuna du, non beste hiri batzuetako eraikinek imitatutako estilo bati izena eman zion.</p>\n<h4>Historia</h4>\n<p>Jauregia 1539an hasi ziren eraikitzen Monterreyko kondearentzat. Jatorrizko proiektuaren zati bat baino ez zen gauzatu, baina nahikoa izan zen Espainiako arkitektura errenazentistaren erreferente bihurtzeko.</p>\n<h4>Bitxikeria</h4>\n<p>Gaur eraikin osoa dirudiena, egiaz, asmo askoz handiago baten zati bat zen. Batzuetan eragin handiena duen arkitektura amaitu gabeko proiektu batetik sortzen da.</p>\n<h4>Non egin argazkia</h4>\n<p>Plazatik, urrundu hego-ekialderantz dorre bat eta goiko galeria diagonalean sartzeko. Ordu honetan saiatu argiak harria laztan dezan. Gutxi gorabeherako orientazioa: ipar-mendebaldea.</p>\n<h4>Nola jarraitu</h4>\n<p>Hartu Bordadores kalea eta jarraitu Fonsecarantz. Zortzi minutu inguru falta dira. Ez geratu gehiegi: helburua 18:40 eta 18:45 artean atean egotea da.</p>",
          "script_path": "../content/eu/dia1/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96445,-5.66859&travelmode=walking",
          "video_url": "../public/media/dia1/parada06.mp4",
          "video_exists": true
        },
        {
          "id": 7,
          "time_rel": "01:40",
          "title": "Colegio Arzobispo Fonseca",
          "short": "Fonseca",
          "lat": 40.9652569,
          "lon": -5.6701508,
          "blurb": "Harrerara iritsi aurretik, atariaren lasaitasuna aprobetxatzeko azken pausa.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Kalearen beste aldetik, fatxada osorik eta presarik gabe.",
          "hidden_detail": "Gaur egungo erabilera kulturala eta unibertsitarioa jatorri errenazentistarekin lotuta jarraitzen du.",
          "image": "../public/images/fonseca.jpg",
          "script_html": "<h3>07 · Arzobispo Fonseca ikastetxea</h3>\n<h4>Sarrera</h4>\n<p>Ibilbidea hemen amaitzen da, arratsaldeko beste zati bat hasten den une berean. Bi ordu baino gutxiagoan Salamanca garaikidetik haren antzinako ikastetxe nagusietako batera iritsi zara.</p>\n<h4>Zer begiratu</h4>\n<p>Sartu aurretik, begiratu fatxada eta ataria. Harrerak patiora pasatzeko aukera ematen badu, utzi audiogida pausatuta: espazio hori azalpenik gabe ikustea merezi du.</p>\n<h4>Historia</h4>\n<p>Alonso de Fonsecak sortu zuen ikastetxea, eta lanak 1519an hasi ziren. Hasieran irakaskuntzarako eta egoitzarako izan zen, eta gaur egun unibertsitate-ostatua, kultur ekitaldiak eta topaketa instituzionalak hartzen ditu.</p>\n<h4>Bitxikeria</h4>\n<p>Ondorengo mendeetan erakunde honi lotutako ikasle katoliko irlandarrengatik, Irlandarren Ikastetxea izenez ere ezagutu zen.</p>\n<h4>Non egin argazkia</h4>\n<p>Kontrako espaloitik, enkoadratu ataria aurrez aurre. Harrerara jendea iristen ari bada, albo pixka bateko hartualdi bat diskretuagoa izango da eta eraikinaren bolumena hobeto erakutsiko du. Ibilbide honetarako ordurik onena: 18:40–18:45.</p>\n<h4>Nola jarraitu</h4>\n<p>Sartu harrerara. Aplikazioaren ibilbidea hemen amaitzen da; ez du hotelerako itzulera automatikorik proposatzen. Bidaiaren aurretik komeni da kongresuko programan baieztatzea harrera benetan Fonseca kalea 4an dela.</p>",
          "script_path": "../content/eu/dia1/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9652569,-5.6701508&travelmode=walking",
          "video_url": "../public/media/dia1/parada07.mp4",
          "video_exists": true
        }
      ]
    },
    {
      "slug": "dia2_goiza",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Goizeko paseo lasaia Salamancan",
      "subtitle": "Egunsentiko argia, ibaia eta harrizko hiriaren lehen isiltasuna",
      "duration": "01:00",
      "summary": "Hotelatik abiatu, Tormesera jaitsi eta alde zaharrera igo, turista gutxien dagoenean.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Zenit Hall88 Studios Salamanca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9702112,-5.6766756&travelmode=walking&waypoints=40.96229,-5.67147|40.9609,-5.6699|40.96022,-5.66918|40.96055,-5.6669|40.96114,-5.66702",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Hotela",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Irteera lasaia, lo dagoen hiria atzean utzi gabe.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Hemen ez dago argazki handirik; onena lehen argia gordetzea da.",
          "hidden_detail": "Eguneko erritmoa hasi aurreko minutuak dira, eta hori da ibilbide honen benetako luxua.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Hau ez da gaurko “ibilaldi nagusia”, eta horregatik da hain baliotsua. Goizeko paseo honek ez du monumentu guztiak kateatu nahi; zure begirada egokitu nahi du. Hemen, hotelaren aurrean, hiriak oraindik ez du bere eguneroko zarata hartu. Autobus-geltokiaren ingurua esnatzen hasiko da laster, baina oraindik badago tarte labur bat non Salamanca ia atariko arnasa balitz bezala sentitzen den.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lehenengo minutuetan argiak nola lantzen dituen fatxaden tonuak. Villamayorreko harria ez da urre kolorekoa berez: eguzki baxuarekin eta aireko hezetasunarekin eraikitzen da kolore hori. Hori da paseo honetako hari ezkutua. Hemendik behera joango gara, baina egia esan gorantz hasiko da zure irakurketa: gero eta hobeto ulertuko duzu hiria zer materialekin eta zer erritmorekin egin den.</p>\n<h4>Historia</h4>\n<p>Hall88 ingurua Salamanca garaikidearen ertza da, unibertsitate-bizitzaren eta eguneroko logistikaren artean. Horrek abantaila bat ematen dio hasiera honi: alde zaharrera ez zara bat-batean iristen, baizik eta trantsizio baten bidez. Hiri historikoetan hori askotan galtzen dugu, zuzenean postalaren erdira salto egiten dugulako.</p>\n<h4>Bitxikeria</h4>\n<p>Harrizko hiri handi askotan bezala, lehen inpresioa ez da beti eraikin ospetsu batek ematen; askotan kalearen kalitateak ematen du. Oinez zoazenean sumatzen duzu zein den espaloien, zuhaitzen, itzalen eta fatxaden arteko oreka. Horregatik komeni da lehen minutuetan ez presaka ateratzea.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez nuke hemen argazki nagusia egingo. Gorde lehen irudi benetan ona zubirako edo ibairako. Hasiera honek balio handiagoa du erritmoa markatzeko, ez albumaren lehen orria betetzeko.</p>\n<h4>Nola jarraitu</h4>\n<p>Joan lasai Puente Romanorantz. Ez pentsatu helmugan bakarrik: jaitsiera bera da gaurko lehen prestaketa. Handik aurrera, Salamanca monumentala ez duzu aurrez aurre soilik ikusiko; urrutitik irakurtzen hasiko zara.</p>",
          "script_path": "../content/eu/dia2_goiza/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada01.mp4",
          "video_exists": true
        },
        {
          "id": 2,
          "time_rel": "00:12",
          "title": "Puente Romano",
          "short": "Zubia",
          "lat": 40.96229,
          "lon": -5.67147,
          "blurb": "Zubi zaharrean, hiria atzealde bihurtzen da eta paisaia nagusi.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Zubiaren erdian baino, zertxobait albo batera, katedralak eta ibai-lerroa batera hartzeko.",
          "hidden_detail": "Gaur ikusten dena ez da erromatar obra osoa, baina ideia erromatarra bai: igarobide sendoa, uraren gainean.",
          "image": "../public/images/generated/puente-romano.svg",
          "script_html": "<h3>02 · Puente Romano</h3>\n<h4>Sarrera</h4>\n<p>Hemen hasten da benetako goizeko magia. Zubira iristean, hiriak atzera egiten du apur bat eta paisaiak hartzen du protagonismoa. Horregatik gustatzen zait geldialdi hau ibilaldiaren hasieran jartzea: Salamanca lehenik silueta gisa ikusten duzu, eta geroago bakarrik xehetasun gisa.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu nola antolatzen diren planoak: behean Tormes, erdian zubiaren arkuen erritmoa, eta atzean dorreak, kupulak eta harlandua. Goizeko lehen argiarekin kontrastea oso leuna izan ohi da, eta horrek aukera ematen du hiriaren masa ulertzeko, ez bakarrik bere apaingarriak.</p>\n<h4>Historia</h4>\n<p>Puente Romano deitzen diogu, eta izena egokia da neurri batean, baina hemen interesgarriena ez da “zenbat geratzen den jatorrizkotik” galdera hutsa. Garrantzitsuena da mendeetan zehar ibaiaren pasabide nagusiaren ideia hemen iraun duela. Zubiak ez du soilik ertzak lotzen; Salamanca nola sartzen eta irteten zen kontatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Zubi zaharrek badute ia beti zerbait zientifikotik. Arkuen forma, karga banaketa, uraren presioa, materialaren higadura… dena dago ikusgai, nahiz eta oinez zoazen bitartean ez pentsatu formula bakar batean ere. Ingeniaritza ona askotan ikusezina da, eta hemen hori ederki antzematen da.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez gelditu arkuen erdiko simetriaren bila bakarrik. Mugitu apur bat, eta bilatu ikuspegi apur bat zeiharra: horrela hiriaren profila, zubiaren lerroa eta ibaiaren mugimendua batera sartzen dira. Goizeko argiak bolumenak hobeto modelatzen ditu horrela.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain ibaiertzera jaitsiko gara. Hori da hurrengo geldialdiaren gakoa: zubia egitura bezala ikusi dugu; handik gutxira, ura eta hezetasuna hiriaren materialekin nola elkartzen diren ikusiko dugu.</p>",
          "script_path": "../content/eu/dia2_goiza/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96229,-5.67147&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada02.mp4",
          "video_exists": true
        },
        {
          "id": 3,
          "time_rel": "00:22",
          "title": "Tormes ibaiertza",
          "short": "Ibaia",
          "lat": 40.9609,
          "lon": -5.6699,
          "blurb": "Hemen Salamanca ez da monumentu multzo bat bakarrik; uraren ertzeko hiri bat ere bada.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Ura bare badago, bilatu islak; haizerik badago, landarediaren eta harrien arteko kontrastea.",
          "hidden_detail": "Egunsentiko argi zeharkakoak Villamayorreko harria eta ibaiaren hezetasuna tonu oso desberdinetan banatzen ditu.",
          "image": "../public/images/generated/ribera-tormes.svg",
          "script_html": "<h3>03 · Tormes ibaiertza</h3>\n<h4>Sarrera</h4>\n<p>Ibaian behera edo haren ertzean zaudenean, Salamanca ez da hain akademikoa, ez hain “postalekoa”. Hemen hiria arnasten da beste modu batean. Uraren presentziak tenperatura aldatzen du, soinua aldatzen du, eta baita argiaren kalitatea ere.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lurzoruaren hezetasunari, landarediaren koloreari eta atzean ageri diren harrizko hormei. Egunsentian oso nabarmena da nola banatzen diren tonuak: harria epelagoa dirudi, ura hotzagoa, eta bien arteko trantsizioa oso sotila da. Hori ez da poesia bakarrik; gainazal bakoitzak argia eta beroa modu desberdinean xurgatzen dituelako gertatzen da.</p>\n<h4>Historia</h4>\n<p>Tormesek Salamanca hornitu, babestu eta mugatu egin du aldi berean. Ibaiak hiriari bizkarra ematen diola esaten da askotan, baina hori egia erdia da. Historikoki, ibaiaren ertza funtzionala zen: garraioa, sarrerak, irteerak, laborantza txikiak, eta hezetasunarekiko etengabeko negoziazioa.</p>\n<h4>Bitxikeria</h4>\n<p>Higadurak hemen erakusten du bere lanik isilena. Harri guztiak ez dira berdin zahartzen, eta ez dute guztiok ura berdin jasaten. Villamayorreko harria ederra da, baina material biguna ere bada; horregatik, uraren, haizearen eta kutsaduraren aurrean berehala irakurtzen dira aldaketak.</p>\n<h4>Non egin argazkia</h4>\n<p>Ura bare badago, islen bila joan. Haize pixka bat badabil, orduan hobe da ertzeko landaredia lehen plano gisa erabiltzea. Bi kasuetan, ez saiatu dena sartzen: hobe da zati bat ondo irakurtzea plano handi bat gaizki egitea baino.</p>\n<h4>Nola jarraitu</h4>\n<p>Handik gutxira Casa Lis agertuko zaigu. Ibaiko lasaitasun honetatik modernismo arin batera pasatuko gara. Kontraste hori da geldialdi hurrengoaren xarma.</p>",
          "script_path": "../content/eu/dia2_goiza/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9609,-5.6699&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada03.mp4",
          "video_exists": true
        },
        {
          "id": 4,
          "time_rel": "00:32",
          "title": "Casa Lis (kanpotik)",
          "short": "Casa Lis",
          "lat": 40.96022,
          "lon": -5.66918,
          "blurb": "Modernismo arina, harrizko hiri klasikoaren alboan.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Kristal eta burdin egitura albo batetik hartu, kurbadurak hobeto nabaritzeko.",
          "hidden_detail": "Casa Lisek erakusten du Salamanca ez dela erromanikoa, gotikoa edo platereskoa bakarrik; XX. mendearen hasierak ere hemen utzi zuen arrastoa.",
          "image": "../public/images/generated/casa-lis.svg",
          "script_html": "<h3>04 · Casa Lis (kanpotik)</h3>\n<h4>Sarrera</h4>\n<p>Casa Lisek beti ematen du sorpresa txiki bat. Salamanca hain sendoa, hain harrizkoa eta hain klasikoa iruditzen zaigunean, bat-batean kristala, burdina eta kurba agertzen dira. Horregatik da interesgarria kanpotik ere: ez dugu barrura sartu behar eraikinak zer esan nahi duen ulertzeko.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu fatxadaren arintasunari. Ez da katedral baten masa, ez jauregi baten horma lodia. Hemen azal bat dago, ia pabiloi moduko zerbait, eta horrek inguruko eraikinekin duen kontrastea oso adierazgarria da. Material gardena eta egitura metalikoa ikusita, berehala sumatzen da beste garai batean gaudela.</p>\n<h4>Historia</h4>\n<p>Casa Lis XX. mendearen hasierako modernismoaren arrastoa da Salamancan. Horrek ez du esan nahi hiria bat-batean modernista bihurtu zenik; alderantziz, hain zuzen. Horregatik da hain deigarria: tradizio sendo baten alboan, beste hizkuntza arkitektoniko batek bere lekua bilatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Askotan, hiri historikoetan modernotasuna “istripu” bat balitz bezala ikusten dugu. Baina askotan modernotasuna da hiriari arnasa ematen diona, kontrastea sortzen duena. Casa Lisek hori egiten du: Salamanca harrizkoa are gehiago nabarmentzen du, hain zuzen arinagoa delako.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez saiatu eraikina aurrez aurre eta lauki perfektuan harrapatzen. Hobe albo batetik, egitura kurboak eta beiraren geruzak irakurtzeko. Horrela hobeto ulertzen da ez dela fatxada apaindu bat bakarrik, baizik eta sistema estetiko oso bat.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain Calixto eta Melibearen Baratzerantz igoko gara. Casa Lisen gardentasunetik landarediaren eta harresiaren arteko tarte intimora pasatuko gara. Oso aldaketa atsegina da oinez.</p>",
          "script_path": "../content/eu/dia2_goiza/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96022,-5.66918&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada04.mp4",
          "video_exists": true
        },
        {
          "id": 5,
          "time_rel": "00:40",
          "title": "Calixto eta Melibearen Baratzea",
          "short": "Baratzea",
          "lat": 40.96055,
          "lon": -5.6669,
          "blurb": "Hemen hiria itxiago sentitzen da, baina ikuspegia zabaldu egiten da.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Baratze barrutik hartu katedralen bolumena, landaredia aurrealdean utzita.",
          "hidden_detail": "Landareen artean dagoen intimitateak La Celestinaren iruditeria elikatzen du, nahiz eta lorategia gaur egunekoa izan neurri handi batean.",
          "image": "../public/images/generated/huerto-calixto.svg",
          "script_html": "<h3>05 · Calixto eta Melibearen Baratzea</h3>\n<h4>Sarrera</h4>\n<p>Baratze honetara iristean, paseoaren tonuak berriro aldatzen dira. Ibaiaren zabaltasunetik eta Casa Lisen arintasunetik, espazio itxiago baina intimoago batera sartzen zara. Hemen Salamanca ez da soilik ikusgarria; kontenplatiboa ere bada.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu landarediaren eta harrizko bolumenen arteko harremanari. Baratzeak ikuspegia iragazten du: ez dizu hiria kolpe bakarrean ematen, hostoen, hormen eta irekiduren artean dosifikatzen dizu. Horregatik funtzionatzen du hain ondo goizean; jende gutxi dagoenean, espazioak bere erritmo propioa mantentzen du.</p>\n<h4>Historia</h4>\n<p>Izenak zuzenean La Celestinaren iruditeriara garamatza. Hori da, neurri batean, espazio honen xarma: benetako paisaia eta literatura memorian nahasten dira. Lorategia gaur ezagutzen dugun moduan ez da Erdi Aroko eszenografia gordina, noski, baina izenak eta kokapenak fikzioaren geruza bat eransten diote.</p>\n<h4>Bitxikeria</h4>\n<p>Baratzeek ere badute zientziatik. Itzalak, orientazioak eta hezetasunak erabakitzen dute zer landarek funtzionatzen duen hobeto eta nola eusten zaion udako beroari. Hiri historiko batean lorategi txiki batek mikroklima propioa sor dezake, eta goizeko lehen orduan hori nabari-nabari dago.</p>\n<h4>Non egin argazkia</h4>\n<p>Bilatu katedralen edo harresien bolumena landarediaren atzetik. Ez hartu dena garbi eta zuzen. Hobe da hostoek irudiari aurreko geruza ematea; horrela lekuaren intimitatea mantentzen da eta ez da ikuspegi hutsa bihurtzen.</p>\n<h4>Nola jarraitu</h4>\n<p>Patio Chicora igaroko gara orain. Oso gertu dago, baina espazioaren eskala aldatzen da: lorategi intimo batetik harrizko antzerki txiki batera pasatuko gara.</p>",
          "script_path": "../content/eu/dia2_goiza/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96055,-5.6669&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada05.mp4",
          "video_exists": true
        },
        {
          "id": 6,
          "time_rel": "00:50",
          "title": "Patio Chico",
          "short": "Patio Chico",
          "lat": 40.96114,
          "lon": -5.66702,
          "blurb": "Hiriaren harrizko teatro txikietako bat da, eskala egokia duena.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Behetik pixka bat gora, dorreen eta hormen geruzak pilatzeko.",
          "hidden_detail": "Goiz-goizetan nabarmenagoa da hemen bolumenen arteko elkarrizketa; jendeak huts egiten ez duelako, baizik eta isiltasunak irakurketa errazten duelako.",
          "image": "../public/images/generated/patio-chico.svg",
          "script_html": "<h3>06 · Patio Chico</h3>\n<h4>Sarrera</h4>\n<p>Patio Chico ez da askotan lehen zerrendetan agertzen, eta agian horregatik mantentzen du halako xarma berezia. Ez da Plaza Mayor bezain handia, ez katedralen barrualdea bezain ospetsua, baina hiria ulertzeko eskala bikaina eskaintzen du.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu hormen, dorreen eta maldaren arteko geruzei. Espazio hau ez da “plaza” handi bat; ia elkarrizketa arkitektoniko bat da. Hemen eraikinen bolumenak elkarren kontra ez, elkarren ondoan irakurtzen dira. Goizeko argi baxuak ertzak nabarmen uzten ditu, eta horrek harrizko gainazala oso plastiko bihurtzen du.</p>\n<h4>Historia</h4>\n<p>Patio Chico ingurua katedralen eta unibertsitate-hiriaren arteko lotura diskretuetako bat da. Hain zuzen, hori da bere indarra: ez du protagonista bakarra. Espazioak berak antolatzen du begirada, eta horregatik leku askotan baino hobeto ulertzen dira Salamanca zaharraren dentsitatea eta geruzak.</p>\n<h4>Bitxikeria</h4>\n<p>Turista asko bertatik igarotzen dira helmuga handiago baterantz, baina goizean, jendea iritsi aurretik, ikusten da espazioak berak zer nolako akustika eta isiltasun maila duen. Hiriaren irakurketa ez da ikusmen kontua bakarrik; soinuen dentsitatea ere bada.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri zertxobait beherago eta zuzendu kamera gorantz. Horrela, hormen eta dorreen gainjartzea hobeto ikusten da, eta lekuak duen “eszenatoki” sentsazioa indartzen da. Hobe plano bertikala horizontal zabalegia baino.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik hotelerako itzulera hasiko dugu. Ez dago zertan beste geldialdi handirik egin: paseoaren azken zatia digestio moduan hartzea da onena, ikusi duzuna barruratzeko.</p>",
          "script_path": "../content/eu/dia2_goiza/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96114,-5.66702&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada06.mp4",
          "video_exists": true
        },
        {
          "id": 7,
          "time_rel": "01:00",
          "title": "Zenit Hall88-era itzulera",
          "short": "Itzulera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Ibilbidea biribiltzeko, berriz ere eguneroko Salamancara itzuli.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Ez da azken argazkirik behar; hobe buruan eramatea argiaren sekuentzia.",
          "hidden_detail": "Ibilaldi motz honek erakusten du hiria ez dela beti distantziaz neurtzen; erritmoz eta begiratzeko moduz ere bai.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>07 · Hall88-era itzulera</h3>\n<h4>Sarrera</h4>\n<p>Eta horrela ixten da zirkulua. Hasierako leku berera itzultzeak badu gauza eder bat: hiria ez da berdina iruditzen, nahiz eta kale berak izan. Orain baduzu barne-erritmo bat, baduzu argiaren sekuentzia bat, eta baduzu Tormesetik igo ondorengo eskala-aldaketa buruan.</p>\n<h4>Zer begiratu</h4>\n<p>Helmuga baino gehiago, saiatu ibilaldiaren arrastoa nabaritzen. Gorputzak badaki jadanik non estutu ziren kaleak, non zabaldu zen paisaia, non agertu zen harria epel, eta non sentitu zen hezetasuna. Horrelako paseo laburretan memoria fisikoa oso garrantzitsua da.</p>\n<h4>Historia</h4>\n<p>Hiri bat ezagutzea ez da datu multzo bat pilatzea. Batzuetan, ondo aukeratutako ordubete batek askoz gehiago ematen du egun osoko lasterketa turistiko batek baino. Goizeko lehen tarte honek hori egiten du: orientazio emozionala eta materiala ematen dizu.</p>\n<h4>Bitxikeria</h4>\n<p>Paseo on baten neurri ona da amaieran beste erritmo batean ibiltzen jarraitzen baduzu. Hau da, helmugara iritsita ere ez baduzu “bukatu” sentsazioa, baizik eta hiria hobeto irakurtzeko prest zaudela sentitzen baduzu. Hori da gida honen helburua.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez dago hemen azken argazki derrigorrezkorik. Nahiago nuke azken irudia buruan uztea: zubiko isiltasuna, ibaiaren hezetasuna, Casa Lisen arintasuna eta Patio Chicoko harria.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik aurrera, nahi baduzu, gosaria lasai hartu edo kongresuko eguna hasi dezakezu. Baina hiria dagoeneko ez duzu atzokoa bezala ikusiko.</p>",
          "script_path": "../content/eu/dia2_goiza/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada07.mp4",
          "video_exists": true
        }
      ]
    },
    {
      "slug": "dia3_goiza",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Katedrala ulertzeko goizeko paseo luzea",
      "subtitle": "Katedrala ibaitik, lorategitik, plazatik eta unibertsitatetik nola aldatzen den ikusteko",
      "duration": "02:22",
      "summary": "Hotelatik abiatu, katedralaren hainbat irudi lotu, gosaldu, eta Fonsecan amaitzen den paseo narratiboa.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Colegio Arzobispo Fonseca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9652569,-5.6701508&travelmode=walking&waypoints=40.96229,-5.67147|40.9609,-5.6699|40.96022,-5.66918|40.96055,-5.6669|40.96114,-5.66702|40.96098,-5.66575|C.%20San%20Pablo%2C%206%2C%2037001%20Salamanca|40.9629585,-5.6656516|40.961442,-5.667218|40.96445,-5.66859",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Irteera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Gaurko paseoak ez du katedrala bisitatu nahi; lehenik, hirian nola agertzen den ikasi nahi du.",
          "seeing": "Oraingoz ez duzu katedrala aurrean. Hori da abantaila. Hiri arruntetik abiatuta, gero ikusiko duzun profila askoz nabarmenago bihurtuko da.",
          "look_now": "Begiratu kalearen erritmoari, itzalen luzerari eta harriak oraindik ez duen distira beroari. Geroago tonu horiek beraiek gidatuko dizute begirada.",
          "photo_tip": "Ez egin lehen argazki nagusia hemen; hobe da lehen ikuspegi handia ibaira iristean gordetzea.",
          "hidden_detail": "Hiria ulertzeko modurik onenetakoa ez da postalaren erdian hastea, baizik eta trantsizioan.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Gaur ez dugu katedrala “ikustera” joango. Gaur hura ulertzen hasiko gara. Horregatik, interesgarria da hain zuzen ere hotelaren inguruko hiri arruntetik abiatzea. Hemen ez dago oraindik postal handirik, eta horrek aukera ematen digu lehen agerpena benetan sentituta jasotzeko. Hiri historikoak hobeto irakurtzen dira beti trantsiziotik sartzen zarenean.</p>\n<h4>Zer begiratu</h4>\n<p>Lehen minutu hauetan ez zaitez eraikinen izenekin obsesionatu. Begiratu kalearen erritmoari, itzalei, espaloiei, eta batez ere harriaren koloreari. Villamayorreko harria ez da beti berdin agertzen; egunsentiko argiak ezti-tonua ematen dio, eta geroago lauago bihurtzen da. Gaurko paseo osoan kolore horrek gidatuko dizu begirada.</p>\n<h4>Historia</h4>\n<p>Hall88 ingurua Salamanca garaikidearen ertza da: autobusa, campusa, trafiko neurtua, eguneroko bizitza. Hori guztia ez da “katedralatik kanpokoa”, alderantziz. Hiri historikoaren benetako neurria ulertzeko, haren kanpo-ertza ere sentitu behar da.</p>\n<h4>Bitxikeria</h4>\n<p>Askotan pentsatzen dugu monumentua dela hiriaren hasiera. Baina ia beti lehenago hasten da kontakizuna: nola iristen zaren, zer uzten duzun atzean, eta nola aldatzen den erritmoa oinez zoazen heinean.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez nuke hemen gaurko lehen argazki handia egingo. Hobe da lehen irudi indartsua ibaiaren edo zubiaren inguruan gordetzea. Horrela benetan sumatuko duzu zer den “agerpena”.</p>\n<h4>Nola jarraitu</h4>\n<p>Joan lasai Puente Romanorantz. Ez pentsatu helmuga bakarrik; jaitsiera bera da gaurko lehen prestaketa.</p>",
          "script_path": "../content/eu/dia3_goiza/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada01.mp4",
          "video_exists": false
        },
        {
          "id": 2,
          "time_rel": "00:18",
          "title": "Puente Romano",
          "short": "Zubia",
          "lat": 40.96229,
          "lon": -5.67147,
          "blurb": "Hemen katedrala lehen aldiz multzo gisa irakurtzen da, ez fatxada gisa.",
          "seeing": "Zubitik, katedrala ez da eraikin bakarra. Hiriko siluetaren erdiko pisua da: dorreak, kupulak eta harlandua, ibaiaren gaineko agerpen bakarrean bilduta.",
          "look_now": "Begiratu zubiaren harrizko erritmoari lehenik, eta gero utzi begirada urrunera joaten. Ikusiko duzu nola hazi zen hiria ibaiaren bestaldetik irakurtzen denean.",
          "photo_tip": "Ez geratu arkuen erdiko simetriaren bila; pauso batzuk mugitu eta hartu zubia eta katedrala lerro berean.",
          "hidden_detail": "Hemendik katedrala ia natural dirudi, baina benetan hiriaren boterea ibaiari erakusteko eraikia dagoen silueta da.",
          "image": "../public/images/generated/puente-romano.svg",
          "script_html": "<h3>02 · Puente Romano</h3>\n<h4>Sarrera</h4>\n<p>Hementxe iristen da lehen errebelazioa. Katedrala ez da oraindik fatxada bat, ezta sarrera nagusi bat ere. Silueta bat da, masa bat, ibaiaren bestaldetik bere burua osorik aurkezten duen hiri-altxamendu bat.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu arkuen erritmoari lehenik, eta gero utzi begirada gorantz joaten. Zubia eta katedrala elkarrekin irakurtzen direnean, ulertzen da Salamanca ez zela soilik barrurantz eraikitako hiria. Kanpotik ikusteko ere eraiki zen. Boterea, fedea eta paisaia lerro bakarrean elkartzen dira hemen.</p>\n<h4>Historia</h4>\n<p>Puente Romanoren zatirik zaharrena erromatarra da, nahiz eta mende askotan berreraiki eta egokitu den. Horrek badu sinbolo indartsu bat: pasabidea lehenik, irudia gero. Baina gaur egun biak batera iristen zaizkigu. Zubia igarobidea da; katedrala helmuga bisuala.</p>\n<h4>Bitxikeria</h4>\n<p>Zubi zaharretan ingeniaritza ona ia ezkutuan dago. Arkuaren forma, pisuaren banaketa, uraren presioaren aurkako erantzuna… dena dago hemen, baina begia ez da soilik teknikan geratzen; teknikak paisaia eraikitzen du.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez gelditu beti erdian. Mugi zaitez zertxobait eta hartu zubia eta katedrala lerro berean, elkarren neurria balitz bezala.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain ibaiertzera jaitsiko gara. Zubitik katedrala irudi oso bat zen; handik gutxira, uraren ondoan, tonu eta gainazalen bidez ulertzen hasiko gara.</p>",
          "script_path": "../content/eu/dia3_goiza/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96229,-5.67147&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada02.mp4",
          "video_exists": false
        },
        {
          "id": 3,
          "time_rel": "00:30",
          "title": "Tormes ibaiertza",
          "short": "Ibaia",
          "lat": 40.9609,
          "lon": -5.6699,
          "blurb": "Ibaiak katedrala urruntzen du, baina aldi berean handiago bihurtzen du.",
          "seeing": "Orain ez zaude zubiaren gainean, baizik eta uraren erritmoaren ondoan. Hemendik katedralaren masa bertikalak eta ibaiaren horizontala elkar neurtzen dituzte.",
          "look_now": "Begiratu uraren gainazalari eta gero harrizko hormei. Ikusi nola aldatzen den katedralaren presentzia ura bare edo mugitu dagoen arabera.",
          "photo_tip": "Islak badaude, aprobetxatu; haizerik badago, erabili ibaiertzeko landaredia lehen plano leun gisa.",
          "hidden_detail": "Goizeko argi baxuak harria eta hezetasuna bereizten ditu; horregatik dirudi hiria hemen gorago baino epelagoa eta hotzagoa aldi berean.",
          "image": "../public/images/generated/ribera-tormes.svg",
          "script_html": "<h3>03 · Tormes ibaiertza</h3>\n<h4>Sarrera</h4>\n<p>Ibaiaren ondoan, katedrala urrundu egiten da, baina ez da txikiagoa bihurtzen. Kontrakoa gertatzen da: uraren zabalera eta zeruaren irekidurak haren presentzia are nabarmenago egiten dute.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu uraren azalera, gero harlanduari, eta azkenik bien arteko kontrasteari. Goizeko argi baxuarekin harria epelagoa ageri da; ura, berriz, hotzagoa eta aldakorragoa. Hori ez da efektu poetiko hutsa. Material bakoitzak argia eta beroa desberdin jasotzen ditu, eta horregatik aldatzen da hiriaren irudia puntu honetatik.</p>\n<h4>Historia</h4>\n<p>Tormesek Salamanca hornitu, babestu eta muga gisa markatu du mendeetan. Katedrala, goian, ez da ibaitik bereizitako pieza; ibaiaren presentziak ematen dio zati bat bere handitasunari. Ibaia kenduta, hiria ez litzateke berdin irakurriko.</p>\n<h4>Bitxikeria</h4>\n<p>Higadura ez da bakarrik arazo tekniko bat. Hiriaren estetika bera moldatzen du. Harri bigunagoek argi zoragarria ematen dute, baina baita zahartze ikusgarriagoa ere. Horregatik Salamanca hain ederra da, eta aldi berean hain hauskorra.</p>\n<h4>Non egin argazkia</h4>\n<p>Islak badaude, aprobetxatu. Ez badaude, erabili ertzeko landaredia lehen plano gisa eta utzi katedrala atzean arnasten.</p>\n<h4>Nola jarraitu</h4>\n<p>Casa Lis aldera mugituko gara orain. Ibaiaren tonu naturaletatik beiraren eta burdinaren arintasunera pasatzea oso modu ona da Salamancaren geruzak ulertzen hasteko.</p>",
          "script_path": "../content/eu/dia3_goiza/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9609,-5.6699&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada03.mp4",
          "video_exists": false
        },
        {
          "id": 4,
          "time_rel": "00:42",
          "title": "Casa Lis eta harresiaren ertza",
          "short": "Casa Lis",
          "lat": 40.96022,
          "lon": -5.66918,
          "blurb": "Hiri modernoa eta katedralaren irudi zaharra elkarren ondoan agertzen diren leku berezia.",
          "seeing": "Casa Lisek beira eta burdina jartzen ditu, eta atzean katedrala harri trinko gisa geratzen da. Kontraste horrek azaltzen du Salamanca ez dela garai bakarreko hiria.",
          "look_now": "Begiratu lehenik Casa Lisen azal arinari. Gero altxa begirada atzeko bolumen zaharragora. Bien artean dago gaurko ibilaldiaren lehen tentsio handietako bat.",
          "photo_tip": "Jarri Casa Lis pixka bat alboan, eta utzi atzean harrizko bolumenak agertzen.",
          "hidden_detail": "Modernotasunak ez du hemen tradizioa hausten; tradizioa are nabarmenago bihurtzen du.",
          "image": "../public/images/generated/casa-lis.svg",
          "script_html": "<h3>04 · Casa Lis eta harresiaren ertza</h3>\n<h4>Sarrera</h4>\n<p>Casa Lisek beti harrapatzen du arreta, eta gaur ere bai. Baina interesgarriena ez da eraikin eder bat ikustea bakarrik. Interesgarriena da haren ondoan katedrala eta harresiaren logika zaharra beste modu batean agertzen direla.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lehenik Casa Lisen azal arinari: beira, egitura, kurba, gardentasuna. Gero altxa begirada atzean dagoen harri trinkoagora. Bi garai ez dira elkarri borrokan ageri. Elkarren neurri bihurtzen dira. Horregatik da leku hau hain baliotsua.</p>\n<h4>Historia</h4>\n<p>Casa Lis XX. mendearen hasierako modernismoaren presentzia argia da Salamancan. Eta harresiaren ertzak gogorarazten digu hiri zaharrak ez zuela bere burua infinituki ireki; mugatu, babestu eta markatu egiten zuen. Bi logika desberdin, metro gutxira.</p>\n<h4>Bitxikeria</h4>\n<p>Modernotasuna askotan gehigarri arrotza balitz bezala azaltzen da hiri historikoetan. Baina hemen ez du “hondatzen”. Kontrastearen bidez, zaharra are zaharrago eta sendoago sentiarazten du.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez hartu Casa Lis bakarrik. Saiatu haren lerro arinak eta atzeko harri zaharragoak irudi berean sartzen.</p>\n<h4>Nola jarraitu</h4>\n<p>Handik gutxira lorategi batera igoko gara. Harriaren eta beiraren arteko tentsiotik, landarediak irudia zatika ematen duen puntu batera.</p>",
          "script_path": "../content/eu/dia3_goiza/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96022,-5.66918&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada04.mp4",
          "video_exists": false
        },
        {
          "id": 5,
          "time_rel": "00:54",
          "title": "Calixto eta Melibearen Baratzea",
          "short": "Baratzea",
          "lat": 40.96055,
          "lon": -5.6669,
          "blurb": "Lorategi honek katedrala monumentu hutsa izatetik paisaia bihurtzen du.",
          "seeing": "Hemen katedrala ez dago plazaren erdian, baizik eta landarediaren, hormaren eta hutsuneen artean agertzen da. Horregatik ulertzen da hobeto hirian nola txertatuta dagoen.",
          "look_now": "Begiratu landareen gainetik ageri diren bolumenei. Ez saiatu dena batera hartzen; utzi hostoek irudia zatika eraikitzen.",
          "photo_tip": "Erabili landaredia aurrealdean, eta hartu katedrala haren gainetik agertzen denean.",
          "hidden_detail": "Lorategiak berak baino gehiago, ikuspegia dosifikatzeko moduak egiten du leku hau berezi.",
          "image": "../public/images/generated/huerto-calixto.svg",
          "script_html": "<h3>05 · Calixto eta Melibearen Baratzea</h3>\n<h4>Sarrera</h4>\n<p>Lorategi honek katedrala ezkutatu egiten du pixka bat, eta horregatik ulertzen da hobeto. Batzuetan eraikin handi bat zuzenean ikustea baino interesgarriagoa da haren presentzia zatika nabaritzea.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu hostoen gainetik ageri diren bolumenei. Hemen katedrala ez da plaza batean jarritako objektu bakarra. Hiriaren ehunean eta paisaian txertatutako masa bat da. Baratzeak, hormek eta hutsuneek irudia dosifikatu egiten dute.</p>\n<h4>Historia</h4>\n<p>Leku hau literaturarekin lotzen da bere izenagatik, baina gaur guretzat interesgarriena beste zerbait da: hiriaren eta naturaren arteko tarte txiki bat eskaintzen du, eta handik katedrala ez da hain monumental sentitzen, baizik eta bizitzeko hiri baten pieza.</p>\n<h4>Bitxikeria</h4>\n<p>Lorategiek mikroklima sortzen dute. Itzalak, hezetasunak eta orientazioak aldatzen dituzte azalaren koloreak eta airearen sentsazioa. Horregatik, puntu honetako katedrala ez da zubitik ikusten zenuen bera.</p>\n<h4>Non egin argazkia</h4>\n<p>Erabili landaredia aurrealdean. Ez garbitu irudia gehiegi. Hobe da lekuaren intimitatea mantentzea.</p>\n<h4>Nola jarraitu</h4>\n<p>Patio Chicora mugituko gara. Orain arte katedrala paisaian txertatuta ikusi dugu; hurrengo puntuan, bere hazkundearen juntura ia ukitzeko moduan izango dugu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96055,-5.6669&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada05.mp4",
          "video_exists": false
        },
        {
          "id": 6,
          "time_rel": "01:06",
          "title": "Patio Chico",
          "short": "Patio Chico",
          "lat": 40.96114,
          "lon": -5.66702,
          "blurb": "Hemen ulertzen da benetan katedral zaharra eta berria nola lotzen diren.",
          "seeing": "Patio Chicotik bi katedralen arteko elkarrizketa irakurtzen da: bolumen erromaniko trinkoagoa eta geroago etorritako handitze gotiko sendoagoa.",
          "look_now": "Begiratu bi piezen arteko loturari, ez bakarrik dorre edo kupula bakar bati. Hemen interesgarriena ez da zatirik politena, baizik eta hazkundearen arrastoa.",
          "photo_tip": "Behetik pixka bat gora hartu, hormen eta dorreen geruzak elkarren gainean ikus daitezen.",
          "hidden_detail": "Katedral berria ez zen zaharra ordezkatzeko egin; haren ondoan, haren gainean ia, hazi zen.",
          "image": "../public/images/generated/patio-chico.svg",
          "script_html": "<h3>06 · Patio Chico</h3>\n<h4>Sarrera</h4>\n<p>Hau da gaurko ibilbideko puntu giltzarrietako bat. Hemen uzten dio katedralak irudi urrun bat izateari, eta historia eraikia bihurtzen da. Pieza zaharra eta pieza berria batera ageri dira.</p>\n<h4>Zer begiratu</h4>\n<p>Ez bilatu “zatirik ederrena”. Begiratu loturari. Nola elkartzen diren bolumenak, nola pilatzen diren hormak, nola aldatu zen eskala mendeen poderioz. Katedral zaharra trinkoagoa, baxuagoa eta barrurantzkoa da; berria handiagoa, ausartagoa, espazio gehiago hartzen duena.</p>\n<h4>Historia</h4>\n<p>Salamancako katedral berria ez zen zaharra botatzeko egin. Haren ondoan, hura zutik mantenduz, handitu zen. Erabaki horrek asko esaten du hiriari buruz: ez du aurrekoa ezabatzen; gainean eraikitzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Eraikuntzaren logika hau ia geologikoa da. Geruza berri bat zaharraren gainean, baina hura estali gabe. Horregatik da hain interesgarria Salamanca: hiriaren historia ez dago testuetan bakarrik, junturetan dago.</p>\n<h4>Non egin argazkia</h4>\n<p>Behetik gora, geruzak bata bestearen gainean ikus daitezen. Ez saiatu dorre bakar bat isolatzen.</p>\n<h4>Nola jarraitu</h4>\n<p>Plaza de Anayara joango gara orain. Hemen juntura irakurri dugu; handik aurrera aurrealde osoa espazio zabalago batek nola aurkezten duen ikusiko dugu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96114,-5.66702&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada06.mp4",
          "video_exists": false
        },
        {
          "id": 7,
          "time_rel": "01:18",
          "title": "Plaza de Anaya",
          "short": "Anaya",
          "lat": 40.96098,
          "lon": -5.66575,
          "blurb": "Katedralaren aurrealdearen eta hura prestatzeko sortutako espazioaren arteko harremana agerian geratzen da.",
          "seeing": "Plaza honek katedralaren aurrealdea antolatzen du. Espazioa zabaldu egiten da, eta eraikinak lehen aldiz aurrez aurreko presentzia handia hartzen du.",
          "look_now": "Gelditu eskaileraren edo plazaren erdiko lerroaren antzeko puntu batean eta begiratu nola prestatzen dizun espazioak fatxada.",
          "photo_tip": "Ez hartu fatxada soilik; sartu plazaren zati bat, bestela galdu egingo da eskalaren joko osoa.",
          "hidden_detail": "Batzuetan plaza batek azaltzen du eraikin bat baino gehiago. Hemen gertatzen den hori da.",
          "image": "../public/images/generated/plaza-anaya.svg",
          "script_html": "<h3>07 · Plaza de Anaya</h3>\n<h4>Sarrera</h4>\n<p>Plaza de Anayara ateratzen zarenean, katedrala beste hizkuntza batean hasten da hitz egiten. Patio Chicoko gertutasun trinkoa atzean utzi, eta orain espazio zabal batek aurrealdea prestatu egiten dizu.</p>\n<h4>Zer begiratu</h4>\n<p>Plaza batek egiten duen lana askotan oharkabean pasatzen da. Hemen plazak ez du soilik katedrala inguratzen: ikusteko modua antolatzen du. Eskala handitu egiten da, fatxada arnasa hartzen hasten da, eta eraikinak lehen aldiz aurrez aurreko presentzia handia hartzen du.</p>\n<h4>Historia</h4>\n<p>Palacio de Anaya eta plaza osoaren antolamenduak frogatzen dute hiri historikoak ez direla monumentuen bilduma kaotiko bat. Espazio publikoaren bidez pentsatuak daude. Katedrala ez dago bakarrik; aurretik duen hutsuneak osatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Askotan eraikinak baino gehiago gogoratzen ditugu haien aurreko plazak. Ez gara konturatzen, baina memoria bisualak oso ondo gordetzen ditu “aurkezpen-lekuak”.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez hartu fatxada bakarrik. Utzi plazaren zati bat barruan, bestela eskalaren jokoa galduko da.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain gosariaren geldialdia egingo dugu. Ez da eten arrunta: orain arte eraiki dugun irudia pausatzeko modu bat da.</p>",
          "script_path": "../content/eu/dia3_goiza/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96098,-5.66575&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada07.mp4",
          "video_exists": false
        },
        {
          "id": 8,
          "time_rel": "01:22",
          "title": "Dale Café",
          "short": "Gosaria",
          "lat": null,
          "lon": null,
          "blurb": "Gosaria pixka bat lehenago dator orain, paseoaren lehen irudi handiak pausatzeko eta hirira berriz itzultzeko.",
          "seeing": "Orain katedralaren irudi handitik atera eta kale biziagora sartzen zara. Horrek ez du kontakizuna hausten; aitzitik, orain arteko ikuspegiak hiriaren eguneroko erritmoarekin lotzen ditu.",
          "look_now": "Begiratu barruko mugimenduari, kafearen lurrunari eta kalearen esnatzeari. Hartu atseden hau benetako trantsizio gisa, ez soilik geldialdi praktiko gisa.",
          "photo_tip": "Barruan, giroa eta katilua; kanpoan, kalearen lehen mugimendua eta sarreraren intimitatea.",
          "hidden_detail": "Zuk probatuta ondo funtzionatu duen gosari-leku batek askotan gida baten benetako balioa handitzen du, ez bakarrik haren fama.",
          "image": "../public/images/generated/dale-cafe.svg",
          "script_html": "<h3>08 · Dale Café</h3>\n<h4>Sarrera</h4>\n<p>Gosaria ez da gaurko ibilbidean parentesi hutsa. Aitzitik: hiriaren irudiak barrura eramateko unea da. Orain arte katedrala hainbat agerpenetan ikusi dugu; hemen, Dale Café-n, paseoaren lehen zatia pausatu eta bigarrena beste erritmo batekin hasiko dugu.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu barruko mugimenduari, kafearen usainari, katiluen erritmoari eta sarreratik ikusten den kaleari. Monumentuz beteriko hiria berriro eguneroko hiri bihurtzen da. Hori da geldialdi honen interesa: orain arteko ikuspegi handi guztiak bizi den Salamanca batekin lotzea.</p>\n<h4>Historia</h4>\n<p>Dale Café hemen sartzeak badu abantaila praktiko eta narratibo bat: goiz irekitzen du, eta paseoaren erdian arnasa hartzeko aukera ematen du katedralaren lehen irudi sendoak jada barruan dituzunean. Ez da soilik gosari teknikoa; ibilbidearen egitura bera da.</p>\n<h4>Bitxikeria</h4>\n<p>Kafe on bat askotan edariak baino gehiago definitzen du. Noiz irekitzen duen, nola hartzen duen jendeak goiza eta ea benetan laguntzen dizun paseo baten erritmoa ez hausten. Horregatik da hobe batzuetan lurrean probatutako tokia izen ospetsu bat baino.</p>\n<h4>Non egin argazkia</h4>\n<p>Barruan, katilua, mahaia eta giroa. Kanpoan, sarrera eta kalearen lehen mugimendua. Ez du zertan gaurko argazkirik ederrena izan; hobe da benetako geldialdiaren memoria izatea.</p>\n<h4>Nola jarraitu</h4>\n<p>Gosaldu ondoren, berriro hiri monumentalera itzuliko gara. Baina orain begirada pausatuagoa izango duzu, eta katedralaren inguruko sare sozial eta arkitektonikoa askoz hobeto irakurriko duzu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada08.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=C.%20San%20Pablo%2C%206%2C%2037001%20Salamanca&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada08.mp4",
          "video_exists": false
        },
        {
          "id": 9,
          "time_rel": "01:46",
          "title": "Casa de las Conchas",
          "short": "Maskorrak",
          "lat": 40.9629585,
          "lon": -5.6656516,
          "blurb": "Katedraletik aldendu arren, hiri monumental osoaren sare sinbolikoa hobeto ulertzen da.",
          "seeing": "Hemen katedrala ez da protagonista, baina haren inguruko Salamanca ulertzeko funtsezko pieza bat bai. Nobleziaren, ordenen eta botere sinbolikoaren hizkuntza ageri da fatxadan.",
          "look_now": "Begiratu maskorren erritmoari, gero ateari, eta azkenik parean duen Clerecíaren presentziari. Hiru begirada horiek batera hartuta irakurtzen da lekua.",
          "photo_tip": "Clerecíaren aldetik, diagonalean, maskorren erritmoa eta espazioaren estutasuna batera hartzeko.",
          "hidden_detail": "Hiri bat ulertzea ez da bere eraikin handiena bakarrik ulertzea; haren inguruko hizkuntza soziala ere bai.",
          "image": "../public/images/casa-conchas.jpg",
          "script_html": "<h3>09 · Casa de las Conchas</h3>\n<h4>Sarrera</h4>\n<p>Gosalditik aterata, monumentuak berriro agertzen dira, baina orain ez dugu katedrala bilatzen bakarrik. Haren inguruko hizkuntza soziala, sinbolikoa eta arkitektonikoa ere irakurtzen hasten gara.</p>\n<h4>Zer begiratu</h4>\n<p>Maskorrak, atea, leihoetako burdin-lana eta pareko masa handiak. Leku hau ez da katedralaren itzalpean dagoen apainketa bitxi bat. Hiri monumentalaren beste alfabeto baten zatia da: boterea, leinua, orden erlijiosoak, erakusgarritasuna.</p>\n<h4>Historia</h4>\n<p>Casa de las Conchas XV. mendearen amaierako eta XVI.aren hasierako eraikina da. Oso bestelako hizkuntza erabiltzen du katedralak baino, baina bien artean hiri bera osatzen da: fedea, noblezia eta prestigio publikoa elkarrizketan.</p>\n<h4>Bitxikeria</h4>\n<p>Hiri bat ez da bere eraikinik handiena bakarrik. Haren zeinu txiki eta errepikakorrek ere osatzen dute identitatea. Hemen maskorrak horixe dira: erritmo sinboliko bat.</p>\n<h4>Non egin argazkia</h4>\n<p>Diagonaletik hartu, maskorren errepikapena eta espazioaren estutasuna nabari daitezen.</p>\n<h4>Nola jarraitu</h4>\n<p>Patio de Escuelaserantz joango gara orain. Han, katedralaren hiriak unibertsitatearen hiriarekin nola egiten duen bat ikusiko dugu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada09.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9629585,-5.6656516&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada09.mp4",
          "video_exists": false
        },
        {
          "id": 10,
          "time_rel": "01:58",
          "title": "Patio de Escuelas",
          "short": "Unibertsitatea",
          "lat": 40.961442,
          "lon": -5.667218,
          "blurb": "Katedralaren hiriaren eta jakintzaren hiriaren arteko elkarrizketa agerian geratzen da.",
          "seeing": "Hemendik unibertsitatea ez da bakarrik fatxada ospetsu bat. Katedralaren munduarekiko auzokidea da, eta biak elkarri neurria ematen diote.",
          "look_now": "Begiratu unibertsitatearen fatxadari, gero patioaren espazioari, eta pentsatu katedrala oso gertu dagoela nahiz eta une honetan ez duzun osorik ikusten.",
          "photo_tip": "Fray Luis lehen planoan edo albo batean utzi, eta fatxadaren erliebeak argi leunarekin hartu.",
          "hidden_detail": "Salamanca ulertzeko, fedearen eta jakintzaren eraikinek elkarren ondoan nola bizi diren ikusi behar da.",
          "image": "../public/images/universidad.jpg",
          "script_html": "<h3>10 · Patio de Escuelas</h3>\n<h4>Sarrera</h4>\n<p>Hemen Salamancaren beste oreka handi bat ageri da: katedrala eta unibertsitatea. Fedearen eta jakintzaren eraikinak, oso gertu, elkarren itzalean baina elkarren kontra ez.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu patioaren espazioari lehenik, eta gero fatxadari. Ez da beharrezkoa katedrala osorik ikustea haren presentzia nabaritzeko. Gertu dagoen masa historikoak espazioa bera baldintzatzen du. Horregatik da interesgarria leku hau: ikusgai dagoena baino gehiago iradokitzen du.</p>\n<h4>Historia</h4>\n<p>Salamancako unibertsitatea eta katedral-multzoa ez dira bi mundu paralelo. Mendeetan zehar elkarri lotuta bizi izan dira, eta hiriaren ospea bi ardatz horien inguruan eraiki da neurri handi batean.</p>\n<h4>Bitxikeria</h4>\n<p>Jende asko igelaren bila dator, eta hori ondo dago. Baina hemen askoz interesgarriagoa da galdetzea zergatik dauden horren gertu bi botere handiak: eliza eta ikasketa.</p>\n<h4>Non egin argazkia</h4>\n<p>Fray Luis edo patioaren zati bat sartuta, fatxadari arnasa emanez. Ez estutu gehiegi planoa.</p>\n<h4>Nola jarraitu</h4>\n<p>Azken geldialdi handira joango gara orain: Monterrey. Katedralaren kontakizunetik ateratzen garenean ere, zergatik jarraitzen duen Salamanca zeru-lerrora begira ulertuko dugu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada10.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.961442,-5.667218&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada10.mp4",
          "video_exists": false
        },
        {
          "id": 11,
          "time_rel": "02:12",
          "title": "Palacio de Monterrey",
          "short": "Monterrey",
          "lat": 40.96445,
          "lon": -5.66859,
          "blurb": "Katedralaren ibilbidea amaitzear dagoenean, hiriko beste zeru-lerro noble bat agertzen da.",
          "seeing": "Jauregi honek erakusten du katedralaren dorreak ez direla bakarrak Salamancako zeru gainean. Hiriaren goiko lerroak hainbat botere eta garaitako siluetak bildu ditu.",
          "look_now": "Begiratu goiko gailurreriari, tximiniei eta dorreei. Galdetu zeure buruari zergatik gogoratzen den hain ondo amaitu gabe dagoen eraikin bat.",
          "photo_tip": "Urrundu pixka bat eta hartu goiko aldearen erritmoa, ez bakarrik sarrera.",
          "hidden_detail": "Hiri baten memoria askotan zeruaren kontra mozten diren formek gidatzen dute.",
          "image": "../public/images/monterrey.jpg",
          "script_html": "<h3>11 · Palacio de Monterrey</h3>\n<h4>Sarrera</h4>\n<p>Monterreyk ez du gaurko gai nagusia ordezkatzen, baina bai osatzen. Katedrala ulertu ondoren, hemendik ikusten da zergatik den hain garrantzitsua Salamancan zeruaren kontra mozten den forma.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu dorreei, gailurreriari eta tximiniei. Jauregia ez da katedrala bezain handia, baina badu antzeko indar bat: gorantz egindako keinua, hiria urrunetik ere identifikatzen laguntzen duena.</p>\n<h4>Historia</h4>\n<p>Monterrey XVI. mendeko proiektu handiago baten zati amaitua da. Hori bera da bere xarma: amaitu gabe egon arren, hiriaren iruditerian leku handia lortu zuen.</p>\n<h4>Bitxikeria</h4>\n<p>Batzuetan amaitu gabeko eraikinek amaitutakoek baino indar gehiago dute. Pentsamendua uzten dutelako lanean, ez dutelako guztia itxita ematen.</p>\n<h4>Non egin argazkia</h4>\n<p>Urrundu pixka bat eta hartu goiko erritmoa. Ez gelditu sarreran bertan.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik Fonsecaraino azken tarte laburra besterik ez da geratzen. Paseo osoa lotzen duen amaiera lasaia da.</p>",
          "script_path": "../content/eu/dia3_goiza/parada11.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96445,-5.66859&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada11.mp4",
          "video_exists": false
        },
        {
          "id": 12,
          "time_rel": "02:22",
          "title": "Colegio Arzobispo Fonseca",
          "short": "Fonseca",
          "lat": 40.9652569,
          "lon": -5.6701508,
          "blurb": "Paseoa hemen ixten da, katedrala ulertzetik hiri akademiko eta instituzionalera itzulita.",
          "seeing": "Fonsecan amaitzeak zentzua du: paseo osoan zehar eliza, unibertsitatea, plaza eta noblezia lotu ditugu, eta hemen berriz ere lotura horiek eguneroko erabilera batean biltzen dira.",
          "look_now": "Begiratu atariari eta fatxadaren lasaitasunari. Ez du katedralaren eskala, baina bai Salamancaren beste botere isilago baten presentzia.",
          "photo_tip": "Kalearen beste aldetik, presarik gabe, fatxada osoa eta sarrerako tentsio lasaia hartzeko.",
          "hidden_detail": "Ibilbidea ez da katedralaren aurrean amaitzen, baizik eta hura posible egin zuen hiri-sarearen beste pieza batean.",
          "image": "../public/images/fonseca.jpg",
          "script_html": "<h3>12 · Colegio Arzobispo Fonseca</h3>\n<h4>Sarrera</h4>\n<p>Eta hemen ixten da zirkulua. Katedrala ulertzeko hasi dugun paseoa hura posible egin zuen hiri-sarearen beste pieza batean amaitzen da: ikasketa, erakundea, eta eguneroko erabilerara itzultzen den historia.</p>\n<h4>Zer begiratu</h4>\n<p>Fonsecak ez du katedralaren dramatismoa, baina badu beste indar bat: neurria, isiltasuna eta iraupena. Hemen ulertzen da Salamanca ez dela eraikin ospetsuen segida bat bakarrik. Sare instituzional eta urbano oso bat da.</p>\n<h4>Historia</h4>\n<p>XVI. mendearen hasieran sortutako ikastetxe honek erakusten du unibertsitate-hiriaren eta eliza-hiriaren arteko lotura ez dela ideia abstraktua. Harrian eta erabileran dago.</p>\n<h4>Bitxikeria</h4>\n<p>Paseo on baten seinaleetako bat da amaieran hiri bera desberdin ikusten baduzu. Ez du zertan monumentu gehiago erakutsi; nahikoa da monumentuak lotzen ikasi izana.</p>\n<h4>Non egin argazkia</h4>\n<p>Kalearen beste aldetik, presarik gabe, fatxada osoa eta sarrerako lasaitasuna hartzeko.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik kongresura joan zaitezke zuzenean. Gaurko ibilbideak bere lana egina du: Salamanca irudi solteetan baino, loturen bidez irakurtzen laguntzea.</p>",
          "script_path": "../content/eu/dia3_goiza/parada12.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9652569,-5.6701508&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada12.mp4",
          "video_exists": false
        }
      ]
    }
  ]
};
