window.GUIDE_DATA = {
  "app": {
    "title": "Salamanca Guide",
    "tagline": "Google Maps-ek oinak gidatzen ditu. PWAk begirada.",
    "defaultRoute": "dia2_goiza"
  },
  "routes": [
    {
      "slug": "dia1",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Lehen arratsaldea: hotelatik Fonsecaraino",
      "subtitle": "Kafea, harri urreztatua eta lehen orientazioa presarik gabe",
      "duration": "01:45",
      "summary": "Kongresuko harrerara iritsi aurretik, hiria lasai irakurtzen hasteko ibilbidea.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Colegio Arzobispo Fonseca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9652569,-5.6701508&travelmode=walking&waypoints=40.9653616,-5.6636406|40.9650282,-5.6640558|40.9629585,-5.6656516|40.961442,-5.667218|40.96445,-5.66859",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Irteera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Hiri garaikidetik alde zaharrerako trantsizio lasaia.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Ez gastatu lehen argazkia hemen; gorde lehen benetako koadroa erdigunerako.",
          "hidden_detail": "Hall88 ingurua muga atsegina da Salamanca egunerokoaren eta monumentalenaren artean.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Irteera: Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Lasai hasi. Gaur arratsaldean ez dugu “Salamanca egin” nahi: hiria irakurtzen ikasi besterik ez dugu egingo. Unibertsitate-auzo moderno batetik abiatu, erdiguneko harri urrezturantz joan eta harrera hasten den leku berean amaituko dugu.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu nola aldatzen den hiria alde zaharrera hurbiltzean: etorbideak estutu egiten dira, trafikoa gutxitzen da eta hareharria fatxadetan nagusitzen hasten da.</p>\n<h4>Historia</h4>\n<p>Hotela Miguel de Unamuno campusaren ondoan dago, autobus-geltokiaren aurrean. Eguneroko Salamanca eta Salamanca monumentala bereizten dituen muga ona da.</p>\n<h4>Bitxikeria</h4>\n<p>Villamayorreko harria ia krema kolorekoa dirudi egunez, baina albo-argiarekin ezti kolorekoa bihurtzen da. Kolore-aldaketa hori izango da paseoaren hari bisuala.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez da beharrezkoa hotela fotografiatzea. Gorde lehen irudia Plaza Mayor agertzen denerako: kontrasteak hobeto kontatuko du iritsiera.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Peña de Francia kaletik eta jarraitu erdigunerantz. Lehen helburua Café Novelty da, hogei minutu ingurura. Gurutza itzazu etorbideak seinaleztatutako pasabideetatik.</p>",
          "script_path": "../content/eu/dia1/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia1/parada01.mp4",
          "video_exists": true
        },
        {
          "id": 2,
          "time_rel": "00:24",
          "title": "Café Novelty",
          "short": "Kafea",
          "lat": 40.9653616,
          "lon": -5.6636406,
          "blurb": "Lehen atsedenaldiak paseoari erritmo egokia ematen dio.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Arkupeen azpitik, diagonalean, plazaren lehen markoa hartu.",
          "hidden_detail": "Kafetegiaren memoria literarioak plazaren ikuspegia baino gehiago ematen du.",
          "image": "../public/images/cafe-novelty.jpg",
          "script_html": "<h3>02 · Café Novelty</h3>\n<h4>Sarrera</h4>\n<p>Atsedenaldira une egokian iritsi zara, eta hori zen asmoa. Sartu Noveltyn 17:23 eta 17:25 artean, eta gorde hogei minutu inguru kafearentzat.</p>\n<h4>Zer begiratu</h4>\n<p>Bilatu hizketarako kafetegi-giroa, ez bakarrik Plazaren ikuspegia. Barruan Gonzalo Torrente Ballesterren eskultura dago, beste bezero bat balitz bezala eserita.</p>\n<h4>Historia</h4>\n<p>Novelty 1905ean ireki zuten, eta Salamancako kafetegirik zaharrena dela aldarrikatzen du. Haren mahaietatik hiriko bizitza kulturalaren zati handi bat igaro zen. Egungo lokalak memoria hori gordetzen du, denborarekin aldatu bada ere.</p>\n<h4>Bitxikeria</h4>\n<p>Torrente Ballesterrek hiri imajinarioei buruz idatzi zuen, baina hemen kafetegiko bizilagun iraunkor bihurtu zen. Tokirik badago, haren ondoan esertzea da geldialdi honetako erritu txikia.</p>\n<h4>Non egin argazkia</h4>\n<p>Egin barruko argazki bat eskulturarantz, beste bezeroei trabarik egin gabe. Kanpoan, jarri arkupeen azpian eta atera Plazaren argazkia diagonalean, arkuekin marko gisa. Gutxi gorabeherako orientazioa: ekialde-ipar-ekialdea.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Noveltytik Plaza Mayorreko erdialderantz. Hurrengo geldialdia minutu bat baino gutxiagora dago: ez hasi oraindik presaka; lehenik begiratu espazio osoa.</p>",
          "script_path": "../content/eu/dia1/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9653616,-5.6636406&travelmode=walking",
          "video_url": "../public/media/dia1/parada02.mp4",
          "video_exists": true
        },
        {
          "id": 3,
          "time_rel": "00:45",
          "title": "Plaza Mayor",
          "short": "Plaza",
          "lat": 40.9650282,
          "lon": -5.6640558,
          "blurb": "Ez helmuga gisa, sarrera handi gisa irakurtzeko plaza.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Erdialdean gelditu eta udaletxerantz zuzendu marko zabala egiteko.",
          "hidden_detail": "Laukia oso orekatua da, baina ez da guztiz simetrikoa.",
          "image": "../public/images/plaza-mayor.jpg",
          "script_html": "<h3>03 · Plaza Mayor</h3>\n<h4>Sarrera</h4>\n<p>Oraingoan Plaza Mayor ez da eguneko amaiera handia, sarrerako atea baizik. Gelditu minutu batzuk bakarrik: bihar beste argi eta beste erritmo batekin itzul zaitezke.</p>\n<h4>Zer begiratu</h4>\n<p>Jarri gutxi gorabehera erdian eta egin bira poliki. Plaza erabat erregularra dirudi, baina pabiloi bakoitzak bere eginkizuna du eta Udaletxeko kanpai-hormak horizontala hausten du.</p>\n<h4>Historia</h4>\n<p>Plaza barrokoa XVIII. mendean eraiki zen. Alberto de Churriguerak abiatu zuen proiektua, eta Andrés García de Quiñonesek osatu zuen multzoaren zati handi bat. Arkuetako medailoiek pertsonaien galeria bihurtzen dute arkupeetako ibilaldia.</p>\n<h4>Bitxikeria</h4>\n<p>Zenbatu aldeak begiradaz: karratu perfektu baten inpresioa ematen du, oinplano erreala hala ez izan arren. Arkitekturak erritmoaren eta errepikapenaren bidez zuzentzen du gure pertzepzioa.</p>\n<h4>Non egin argazkia</h4>\n<p>Erdigunetik, enkoadratu Udaletxea bertikalean; argazki lasaiago baterako, erabili arkupeetako arkuetako bat marko gisa. Ordu honetan argia gogorra izan daiteke: neurtu harrirako eta utzi zerua pixka bat argiago.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten plazatik hego-mendebaldeko irteeratik eta hartu Rúa Mayor. Bost minutu inguruan aurrez aurre agertuko dira Casa de las Conchas eta Clerecía.</p>",
          "script_path": "../content/eu/dia1/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9650282,-5.6640558&travelmode=walking",
          "video_url": "../public/media/dia1/parada03.mp4",
          "video_exists": true
        },
        {
          "id": 4,
          "time_rel": "00:57",
          "title": "Casa de las Conchas",
          "short": "Maskorrak",
          "lat": 40.9629585,
          "lon": -5.6656516,
          "blurb": "Fatxada bakarra eta Clerecíarekin duen elkarrizketa bisuala.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Clerecíaren aldetik, diagonalean, maskorren erritmoa hobeto ikusten da.",
          "hidden_detail": "Fatxada osoa ez da apaindura hutsa; botere sinbolikoaren erakusketa ere bada.",
          "image": "../public/images/casa-conchas.jpg",
          "script_html": "<h3>04 · Casa de las Conchas</h3>\n<h4>Sarrera</h4>\n<p>Hemen Salamancak liburu eta igarkizun izatera jokatzen du. Ez da barrura sartu behar: fatxadak berak kontatzen du leinuen, sinboloen eta prestigioaren historia.</p>\n<h4>Zer begiratu</h4>\n<p>Ez begiratu maskorrei bakarrik. Erreparatu leihoetako saretei, ateari eta aurrez aurre dauden Clerecíako dorreekin duen elkarrizketari. Espazioa estua da eta gora begiratzera behartzen du.</p>\n<h4>Historia</h4>\n<p>Jauregia XV. mendearen amaiera eta XVI.aren hasiera artean eraiki zuten Rodrigo Arias Maldonadorentzat. Maskorrak Santiago Ordenarekin lotzen dira, baina baita Pimentel familiaren ikurrarekin ere.</p>\n<h4>Bitxikeria</h4>\n<p>Kondairak dio maskorretako batek altxor bat ezkutatzen duela. Istorio ezin hobea da fatxada errepikakor baterako: dena berdina dirudienean, salbuespena bilatzen hasten gara.</p>\n<h4>Non egin argazkia</h4>\n<p>Gurutzatu Clerecíarantz eta erabili angelu zabal samarra. Maskorren erritmoa harrapatzeko, atera argazkia diagonalean fatxadaren iparraldeko muturretik. Orientazioa: mendebalde-hego-mendebaldea.</p>\n<h4>Nola jarraitu</h4>\n<p>Jarraitu Libreros kaletik eta biratu Patio de Escuelaserantz. Lau minutu inguruko bidea da oinez. Han bilatu Unibertsitatearen fatxada historikoa eta Fray Luis de Leónen estatua.</p>",
          "script_path": "../content/eu/dia1/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9629585,-5.6656516&travelmode=walking",
          "video_url": "../public/media/dia1/parada04.mp4",
          "video_exists": true
        },
        {
          "id": 5,
          "time_rel": "01:10",
          "title": "Unibertsitatea eta Patio de Escuelas",
          "short": "Unibertsitatea",
          "lat": 40.961442,
          "lon": -5.667218,
          "blurb": "Ikur handiak lehen begiratuan baino lasaiago irakurtzeko tokia.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Fray Luis lehen planoan utzi eta fatxada pixka bat alboratuta hartu.",
          "hidden_detail": "Jende gehiena igelaren bila hasten da eta eskulturaren kontakizun osoa galtzen du.",
          "image": "../public/images/universidad.jpg",
          "script_html": "<h3>05 · Unibertsitatea, Patio de Escuelas</h3>\n<h4>Sarrera</h4>\n<p>Patio hau eszenatoki txiki bat da. Jarri Fray Luis de León ondoan eta utzi estatuak nora begiratu esaten: fatxada ia harrizko orrialde bat da.</p>\n<h4>Zer begiratu</h4>\n<p>Igo begirada fatxadan behetik gora. Lehenik Errege Katolikoak, gero armarrien eta medailoien eremua, eta azkenik zatirik sinbolikoena. Ez bihurtu igela bilaketa urduri batean; multzoak jokoak baino gehiago balio du.</p>\n<h4>Historia</h4>\n<p>Salamancako Unibertsitatearen jatorria 1218ra doa. Fatxada plateresko ospetsua geroagokoa da, XVI. mendearen hasierakoa, eta boterea, ezagutza eta monarkia programa bisual beraren zati gisa aurkezten ditu.</p>\n<h4>Bitxikeria</h4>\n<p>Igela garezur baten gainean dago. Ikasleen tradizioak zorte akademikoa agintzen dio aurkitzen duenari, baina agian zentzuzkoena beste ikasgai bat da: arreta handiz begiratzeak beti laguntzen du azterketa batean.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri Fray Luisen atzean edo pixka bat albo batean haren silueta eta fatxada batera sartzeko. Orientazioa: mendebaldea. Erliebeetarako, erabili zooma eta saihestu mugikorra gehiegi makurtzea.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Patio de Escuelasetik Compañía kalerantz eta egin aurrera ipar-mendebaldera. Ibilbideak Monterrey jauregira eramango zaitu hamar minutu inguruan; Fonsecaren aurreko argazki-geldialdi laburra da.</p>",
          "script_path": "../content/eu/dia1/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.961442,-5.667218&travelmode=walking",
          "video_url": "../public/media/dia1/parada05.mp4",
          "video_exists": true
        },
        {
          "id": 6,
          "time_rel": "01:28",
          "title": "Palacio de Monterrey",
          "short": "Monterrey",
          "lat": 40.96445,
          "lon": -5.66859,
          "blurb": "Geldialdi labur baina oso fotogenikoa.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Hobe diagonalean, dorreak eta gailurreria batera sartzeko.",
          "hidden_detail": "Eraikin amaitu gabe batek estilo oso baten iruditeria markatu zuen.",
          "image": "../public/images/monterrey.jpg",
          "script_html": "<h3>06 · Monterrey jauregia</h3>\n<h4>Sarrera</h4>\n<p>Hau bost minutuko etenaldia da, ez bisita osoa. Jauregiak unibertsitate-gunearen eta Fonsecaren arteko giltza-lana egiten du.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu zeruaren kontra moztutako gailurreria, dorreak eta tximiniak. Goiko aldeak hainbesteko nortasuna du, non beste hiri batzuetako eraikinek imitatutako estilo bati izena eman zion.</p>\n<h4>Historia</h4>\n<p>Jauregia 1539an hasi ziren eraikitzen Monterreyko kondearentzat. Jatorrizko proiektuaren zati bat baino ez zen gauzatu, baina nahikoa izan zen Espainiako arkitektura errenazentistaren erreferente bihurtzeko.</p>\n<h4>Bitxikeria</h4>\n<p>Gaur eraikin osoa dirudiena, egiaz, asmo askoz handiago baten zati bat zen. Batzuetan eragin handiena duen arkitektura amaitu gabeko proiektu batetik sortzen da.</p>\n<h4>Non egin argazkia</h4>\n<p>Plazatik, urrundu hego-ekialderantz dorre bat eta goiko galeria diagonalean sartzeko. Ordu honetan saiatu argiak harria laztan dezan. Gutxi gorabeherako orientazioa: ipar-mendebaldea.</p>\n<h4>Nola jarraitu</h4>\n<p>Hartu Bordadores kalea eta jarraitu Fonsecarantz. Zortzi minutu inguru falta dira. Ez geratu gehiegi: helburua 18:40 eta 18:45 artean atean egotea da.</p>",
          "script_path": "../content/eu/dia1/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96445,-5.66859&travelmode=walking",
          "video_url": "../public/media/dia1/parada06.mp4",
          "video_exists": true
        },
        {
          "id": 7,
          "time_rel": "01:40",
          "title": "Colegio Arzobispo Fonseca",
          "short": "Fonseca",
          "lat": 40.9652569,
          "lon": -5.6701508,
          "blurb": "Harrerara iritsi aurretik, atariaren lasaitasuna aprobetxatzeko azken pausa.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Kalearen beste aldetik, fatxada osorik eta presarik gabe.",
          "hidden_detail": "Gaur egungo erabilera kulturala eta unibertsitarioa jatorri errenazentistarekin lotuta jarraitzen du.",
          "image": "../public/images/fonseca.jpg",
          "script_html": "<h3>07 · Arzobispo Fonseca ikastetxea</h3>\n<h4>Sarrera</h4>\n<p>Ibilbidea hemen amaitzen da, arratsaldeko beste zati bat hasten den une berean. Bi ordu baino gutxiagoan Salamanca garaikidetik haren antzinako ikastetxe nagusietako batera iritsi zara.</p>\n<h4>Zer begiratu</h4>\n<p>Sartu aurretik, begiratu fatxada eta ataria. Harrerak patiora pasatzeko aukera ematen badu, utzi audiogida pausatuta: espazio hori azalpenik gabe ikustea merezi du.</p>\n<h4>Historia</h4>\n<p>Alonso de Fonsecak sortu zuen ikastetxea, eta lanak 1519an hasi ziren. Hasieran irakaskuntzarako eta egoitzarako izan zen, eta gaur egun unibertsitate-ostatua, kultur ekitaldiak eta topaketa instituzionalak hartzen ditu.</p>\n<h4>Bitxikeria</h4>\n<p>Ondorengo mendeetan erakunde honi lotutako ikasle katoliko irlandarrengatik, Irlandarren Ikastetxea izenez ere ezagutu zen.</p>\n<h4>Non egin argazkia</h4>\n<p>Kontrako espaloitik, enkoadratu ataria aurrez aurre. Harrerara jendea iristen ari bada, albo pixka bateko hartualdi bat diskretuagoa izango da eta eraikinaren bolumena hobeto erakutsiko du. Ibilbide honetarako ordurik onena: 18:40–18:45.</p>\n<h4>Nola jarraitu</h4>\n<p>Sartu harrerara. Aplikazioaren ibilbidea hemen amaitzen da; ez du hotelerako itzulera automatikorik proposatzen. Bidaiaren aurretik komeni da kongresuko programan baieztatzea harrera benetan Fonseca kalea 4an dela.</p>",
          "script_path": "../content/eu/dia1/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9652569,-5.6701508&travelmode=walking",
          "video_url": "../public/media/dia1/parada07.mp4",
          "video_exists": true
        }
      ]
    },
    {
      "slug": "dia2_goiza",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Goizeko paseo lasaia Salamancan",
      "subtitle": "Egunsentiko argia, ibaia eta harrizko hiriaren lehen isiltasuna",
      "duration": "01:00",
      "summary": "Hotelatik abiatu, Tormesera jaitsi eta alde zaharrera igo, turista gutxien dagoenean.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Zenit Hall88 Studios Salamanca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9702112,-5.6766756&travelmode=walking&waypoints=40.96229,-5.67147|40.9609,-5.6699|40.96022,-5.66918|40.96055,-5.6669|40.96114,-5.66702",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Hotela",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Irteera lasaia, lo dagoen hiria atzean utzi gabe.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Hemen ez dago argazki handirik; onena lehen argia gordetzea da.",
          "hidden_detail": "Eguneko erritmoa hasi aurreko minutuak dira, eta hori da ibilbide honen benetako luxua.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Hau ez da gaurko “ibilaldi nagusia”, eta horregatik da hain baliotsua. Goizeko paseo honek ez du monumentu guztiak kateatu nahi; zure begirada egokitu nahi du. Hemen, hotelaren aurrean, hiriak oraindik ez du bere eguneroko zarata hartu. Autobus-geltokiaren ingurua esnatzen hasiko da laster, baina oraindik badago tarte labur bat non Salamanca ia atariko arnasa balitz bezala sentitzen den.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lehenengo minutuetan argiak nola lantzen dituen fatxaden tonuak. Villamayorreko harria ez da urre kolorekoa berez: eguzki baxuarekin eta aireko hezetasunarekin eraikitzen da kolore hori. Hori da paseo honetako hari ezkutua. Hemendik behera joango gara, baina egia esan gorantz hasiko da zure irakurketa: gero eta hobeto ulertuko duzu hiria zer materialekin eta zer erritmorekin egin den.</p>\n<h4>Historia</h4>\n<p>Hall88 ingurua Salamanca garaikidearen ertza da, unibertsitate-bizitzaren eta eguneroko logistikaren artean. Horrek abantaila bat ematen dio hasiera honi: alde zaharrera ez zara bat-batean iristen, baizik eta trantsizio baten bidez. Hiri historikoetan hori askotan galtzen dugu, zuzenean postalaren erdira salto egiten dugulako.</p>\n<h4>Bitxikeria</h4>\n<p>Harrizko hiri handi askotan bezala, lehen inpresioa ez da beti eraikin ospetsu batek ematen; askotan kalearen kalitateak ematen du. Oinez zoazenean sumatzen duzu zein den espaloien, zuhaitzen, itzalen eta fatxaden arteko oreka. Horregatik komeni da lehen minutuetan ez presaka ateratzea.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez nuke hemen argazki nagusia egingo. Gorde lehen irudi benetan ona zubirako edo ibairako. Hasiera honek balio handiagoa du erritmoa markatzeko, ez albumaren lehen orria betetzeko.</p>\n<h4>Nola jarraitu</h4>\n<p>Joan lasai Puente Romanorantz. Ez pentsatu helmugan bakarrik: jaitsiera bera da gaurko lehen prestaketa. Handik aurrera, Salamanca monumentala ez duzu aurrez aurre soilik ikusiko; urrutitik irakurtzen hasiko zara.</p>",
          "script_path": "../content/eu/dia2_goiza/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada01.mp4",
          "video_exists": true
        },
        {
          "id": 2,
          "time_rel": "00:12",
          "title": "Puente Romano",
          "short": "Zubia",
          "lat": 40.96229,
          "lon": -5.67147,
          "blurb": "Zubi zaharrean, hiria atzealde bihurtzen da eta paisaia nagusi.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Zubiaren erdian baino, zertxobait albo batera, katedralak eta ibai-lerroa batera hartzeko.",
          "hidden_detail": "Gaur ikusten dena ez da erromatar obra osoa, baina ideia erromatarra bai: igarobide sendoa, uraren gainean.",
          "image": "../public/images/generated/puente-romano.svg",
          "script_html": "<h3>02 · Puente Romano</h3>\n<h4>Sarrera</h4>\n<p>Hemen hasten da benetako goizeko magia. Zubira iristean, hiriak atzera egiten du apur bat eta paisaiak hartzen du protagonismoa. Horregatik gustatzen zait geldialdi hau ibilaldiaren hasieran jartzea: Salamanca lehenik silueta gisa ikusten duzu, eta geroago bakarrik xehetasun gisa.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu nola antolatzen diren planoak: behean Tormes, erdian zubiaren arkuen erritmoa, eta atzean dorreak, kupulak eta harlandua. Goizeko lehen argiarekin kontrastea oso leuna izan ohi da, eta horrek aukera ematen du hiriaren masa ulertzeko, ez bakarrik bere apaingarriak.</p>\n<h4>Historia</h4>\n<p>Puente Romano deitzen diogu, eta izena egokia da neurri batean, baina hemen interesgarriena ez da “zenbat geratzen den jatorrizkotik” galdera hutsa. Garrantzitsuena da mendeetan zehar ibaiaren pasabide nagusiaren ideia hemen iraun duela. Zubiak ez du soilik ertzak lotzen; Salamanca nola sartzen eta irteten zen kontatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Zubi zaharrek badute ia beti zerbait zientifikotik. Arkuen forma, karga banaketa, uraren presioa, materialaren higadura… dena dago ikusgai, nahiz eta oinez zoazen bitartean ez pentsatu formula bakar batean ere. Ingeniaritza ona askotan ikusezina da, eta hemen hori ederki antzematen da.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez gelditu arkuen erdiko simetriaren bila bakarrik. Mugitu apur bat, eta bilatu ikuspegi apur bat zeiharra: horrela hiriaren profila, zubiaren lerroa eta ibaiaren mugimendua batera sartzen dira. Goizeko argiak bolumenak hobeto modelatzen ditu horrela.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain ibaiertzera jaitsiko gara. Hori da hurrengo geldialdiaren gakoa: zubia egitura bezala ikusi dugu; handik gutxira, ura eta hezetasuna hiriaren materialekin nola elkartzen diren ikusiko dugu.</p>",
          "script_path": "../content/eu/dia2_goiza/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96229,-5.67147&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada02.mp4",
          "video_exists": true
        },
        {
          "id": 3,
          "time_rel": "00:22",
          "title": "Tormes ibaiertza",
          "short": "Ibaia",
          "lat": 40.9609,
          "lon": -5.6699,
          "blurb": "Hemen Salamanca ez da monumentu multzo bat bakarrik; uraren ertzeko hiri bat ere bada.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Ura bare badago, bilatu islak; haizerik badago, landarediaren eta harrien arteko kontrastea.",
          "hidden_detail": "Egunsentiko argi zeharkakoak Villamayorreko harria eta ibaiaren hezetasuna tonu oso desberdinetan banatzen ditu.",
          "image": "../public/images/generated/ribera-tormes.svg",
          "script_html": "<h3>03 · Tormes ibaiertza</h3>\n<h4>Sarrera</h4>\n<p>Ibaian behera edo haren ertzean zaudenean, Salamanca ez da hain akademikoa, ez hain “postalekoa”. Hemen hiria arnasten da beste modu batean. Uraren presentziak tenperatura aldatzen du, soinua aldatzen du, eta baita argiaren kalitatea ere.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lurzoruaren hezetasunari, landarediaren koloreari eta atzean ageri diren harrizko hormei. Egunsentian oso nabarmena da nola banatzen diren tonuak: harria epelagoa dirudi, ura hotzagoa, eta bien arteko trantsizioa oso sotila da. Hori ez da poesia bakarrik; gainazal bakoitzak argia eta beroa modu desberdinean xurgatzen dituelako gertatzen da.</p>\n<h4>Historia</h4>\n<p>Tormesek Salamanca hornitu, babestu eta mugatu egin du aldi berean. Ibaiak hiriari bizkarra ematen diola esaten da askotan, baina hori egia erdia da. Historikoki, ibaiaren ertza funtzionala zen: garraioa, sarrerak, irteerak, laborantza txikiak, eta hezetasunarekiko etengabeko negoziazioa.</p>\n<h4>Bitxikeria</h4>\n<p>Higadurak hemen erakusten du bere lanik isilena. Harri guztiak ez dira berdin zahartzen, eta ez dute guztiok ura berdin jasaten. Villamayorreko harria ederra da, baina material biguna ere bada; horregatik, uraren, haizearen eta kutsaduraren aurrean berehala irakurtzen dira aldaketak.</p>\n<h4>Non egin argazkia</h4>\n<p>Ura bare badago, islen bila joan. Haize pixka bat badabil, orduan hobe da ertzeko landaredia lehen plano gisa erabiltzea. Bi kasuetan, ez saiatu dena sartzen: hobe da zati bat ondo irakurtzea plano handi bat gaizki egitea baino.</p>\n<h4>Nola jarraitu</h4>\n<p>Handik gutxira Casa Lis agertuko zaigu. Ibaiko lasaitasun honetatik modernismo arin batera pasatuko gara. Kontraste hori da geldialdi hurrengoaren xarma.</p>",
          "script_path": "../content/eu/dia2_goiza/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9609,-5.6699&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada03.mp4",
          "video_exists": true
        },
        {
          "id": 4,
          "time_rel": "00:32",
          "title": "Casa Lis (kanpotik)",
          "short": "Casa Lis",
          "lat": 40.96022,
          "lon": -5.66918,
          "blurb": "Modernismo arina, harrizko hiri klasikoaren alboan.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Kristal eta burdin egitura albo batetik hartu, kurbadurak hobeto nabaritzeko.",
          "hidden_detail": "Casa Lisek erakusten du Salamanca ez dela erromanikoa, gotikoa edo platereskoa bakarrik; XX. mendearen hasierak ere hemen utzi zuen arrastoa.",
          "image": "../public/images/generated/casa-lis.svg",
          "script_html": "<h3>04 · Casa Lis (kanpotik)</h3>\n<h4>Sarrera</h4>\n<p>Casa Lisek beti ematen du sorpresa txiki bat. Salamanca hain sendoa, hain harrizkoa eta hain klasikoa iruditzen zaigunean, bat-batean kristala, burdina eta kurba agertzen dira. Horregatik da interesgarria kanpotik ere: ez dugu barrura sartu behar eraikinak zer esan nahi duen ulertzeko.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu fatxadaren arintasunari. Ez da katedral baten masa, ez jauregi baten horma lodia. Hemen azal bat dago, ia pabiloi moduko zerbait, eta horrek inguruko eraikinekin duen kontrastea oso adierazgarria da. Material gardena eta egitura metalikoa ikusita, berehala sumatzen da beste garai batean gaudela.</p>\n<h4>Historia</h4>\n<p>Casa Lis XX. mendearen hasierako modernismoaren arrastoa da Salamancan. Horrek ez du esan nahi hiria bat-batean modernista bihurtu zenik; alderantziz, hain zuzen. Horregatik da hain deigarria: tradizio sendo baten alboan, beste hizkuntza arkitektoniko batek bere lekua bilatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Askotan, hiri historikoetan modernotasuna “istripu” bat balitz bezala ikusten dugu. Baina askotan modernotasuna da hiriari arnasa ematen diona, kontrastea sortzen duena. Casa Lisek hori egiten du: Salamanca harrizkoa are gehiago nabarmentzen du, hain zuzen arinagoa delako.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez saiatu eraikina aurrez aurre eta lauki perfektuan harrapatzen. Hobe albo batetik, egitura kurboak eta beiraren geruzak irakurtzeko. Horrela hobeto ulertzen da ez dela fatxada apaindu bat bakarrik, baizik eta sistema estetiko oso bat.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain Calixto eta Melibearen Baratzerantz igoko gara. Casa Lisen gardentasunetik landarediaren eta harresiaren arteko tarte intimora pasatuko gara. Oso aldaketa atsegina da oinez.</p>",
          "script_path": "../content/eu/dia2_goiza/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96022,-5.66918&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada04.mp4",
          "video_exists": true
        },
        {
          "id": 5,
          "time_rel": "00:40",
          "title": "Calixto eta Melibearen Baratzea",
          "short": "Baratzea",
          "lat": 40.96055,
          "lon": -5.6669,
          "blurb": "Hemen hiria itxiago sentitzen da, baina ikuspegia zabaldu egiten da.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Baratze barrutik hartu katedralen bolumena, landaredia aurrealdean utzita.",
          "hidden_detail": "Landareen artean dagoen intimitateak La Celestinaren iruditeria elikatzen du, nahiz eta lorategia gaur egunekoa izan neurri handi batean.",
          "image": "../public/images/generated/huerto-calixto.svg",
          "script_html": "<h3>05 · Calixto eta Melibearen Baratzea</h3>\n<h4>Sarrera</h4>\n<p>Baratze honetara iristean, paseoaren tonuak berriro aldatzen dira. Ibaiaren zabaltasunetik eta Casa Lisen arintasunetik, espazio itxiago baina intimoago batera sartzen zara. Hemen Salamanca ez da soilik ikusgarria; kontenplatiboa ere bada.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu landarediaren eta harrizko bolumenen arteko harremanari. Baratzeak ikuspegia iragazten du: ez dizu hiria kolpe bakarrean ematen, hostoen, hormen eta irekiduren artean dosifikatzen dizu. Horregatik funtzionatzen du hain ondo goizean; jende gutxi dagoenean, espazioak bere erritmo propioa mantentzen du.</p>\n<h4>Historia</h4>\n<p>Izenak zuzenean La Celestinaren iruditeriara garamatza. Hori da, neurri batean, espazio honen xarma: benetako paisaia eta literatura memorian nahasten dira. Lorategia gaur ezagutzen dugun moduan ez da Erdi Aroko eszenografia gordina, noski, baina izenak eta kokapenak fikzioaren geruza bat eransten diote.</p>\n<h4>Bitxikeria</h4>\n<p>Baratzeek ere badute zientziatik. Itzalak, orientazioak eta hezetasunak erabakitzen dute zer landarek funtzionatzen duen hobeto eta nola eusten zaion udako beroari. Hiri historiko batean lorategi txiki batek mikroklima propioa sor dezake, eta goizeko lehen orduan hori nabari-nabari dago.</p>\n<h4>Non egin argazkia</h4>\n<p>Bilatu katedralen edo harresien bolumena landarediaren atzetik. Ez hartu dena garbi eta zuzen. Hobe da hostoek irudiari aurreko geruza ematea; horrela lekuaren intimitatea mantentzen da eta ez da ikuspegi hutsa bihurtzen.</p>\n<h4>Nola jarraitu</h4>\n<p>Patio Chicora igaroko gara orain. Oso gertu dago, baina espazioaren eskala aldatzen da: lorategi intimo batetik harrizko antzerki txiki batera pasatuko gara.</p>",
          "script_path": "../content/eu/dia2_goiza/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96055,-5.6669&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada05.mp4",
          "video_exists": true
        },
        {
          "id": 6,
          "time_rel": "00:50",
          "title": "Patio Chico",
          "short": "Patio Chico",
          "lat": 40.96114,
          "lon": -5.66702,
          "blurb": "Hiriaren harrizko teatro txikietako bat da, eskala egokia duena.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Behetik pixka bat gora, dorreen eta hormen geruzak pilatzeko.",
          "hidden_detail": "Goiz-goizetan nabarmenagoa da hemen bolumenen arteko elkarrizketa; jendeak huts egiten ez duelako, baizik eta isiltasunak irakurketa errazten duelako.",
          "image": "../public/images/generated/patio-chico.svg",
          "script_html": "<h3>06 · Patio Chico</h3>\n<h4>Sarrera</h4>\n<p>Patio Chico ez da askotan lehen zerrendetan agertzen, eta agian horregatik mantentzen du halako xarma berezia. Ez da Plaza Mayor bezain handia, ez katedralen barrualdea bezain ospetsua, baina hiria ulertzeko eskala bikaina eskaintzen du.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu hormen, dorreen eta maldaren arteko geruzei. Espazio hau ez da “plaza” handi bat; ia elkarrizketa arkitektoniko bat da. Hemen eraikinen bolumenak elkarren kontra ez, elkarren ondoan irakurtzen dira. Goizeko argi baxuak ertzak nabarmen uzten ditu, eta horrek harrizko gainazala oso plastiko bihurtzen du.</p>\n<h4>Historia</h4>\n<p>Patio Chico ingurua katedralen eta unibertsitate-hiriaren arteko lotura diskretuetako bat da. Hain zuzen, hori da bere indarra: ez du protagonista bakarra. Espazioak berak antolatzen du begirada, eta horregatik leku askotan baino hobeto ulertzen dira Salamanca zaharraren dentsitatea eta geruzak.</p>\n<h4>Bitxikeria</h4>\n<p>Turista asko bertatik igarotzen dira helmuga handiago baterantz, baina goizean, jendea iritsi aurretik, ikusten da espazioak berak zer nolako akustika eta isiltasun maila duen. Hiriaren irakurketa ez da ikusmen kontua bakarrik; soinuen dentsitatea ere bada.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri zertxobait beherago eta zuzendu kamera gorantz. Horrela, hormen eta dorreen gainjartzea hobeto ikusten da, eta lekuak duen “eszenatoki” sentsazioa indartzen da. Hobe plano bertikala horizontal zabalegia baino.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik hotelerako itzulera hasiko dugu. Ez dago zertan beste geldialdi handirik egin: paseoaren azken zatia digestio moduan hartzea da onena, ikusi duzuna barruratzeko.</p>",
          "script_path": "../content/eu/dia2_goiza/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96114,-5.66702&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada06.mp4",
          "video_exists": true
        },
        {
          "id": 7,
          "time_rel": "01:00",
          "title": "Zenit Hall88-era itzulera",
          "short": "Itzulera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Ibilbidea biribiltzeko, berriz ere eguneroko Salamancara itzuli.",
          "seeing": null,
          "look_now": null,
          "photo_tip": "Ez da azken argazkirik behar; hobe buruan eramatea argiaren sekuentzia.",
          "hidden_detail": "Ibilaldi motz honek erakusten du hiria ez dela beti distantziaz neurtzen; erritmoz eta begiratzeko moduz ere bai.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>07 · Hall88-era itzulera</h3>\n<h4>Sarrera</h4>\n<p>Eta horrela ixten da zirkulua. Hasierako leku berera itzultzeak badu gauza eder bat: hiria ez da berdina iruditzen, nahiz eta kale berak izan. Orain baduzu barne-erritmo bat, baduzu argiaren sekuentzia bat, eta baduzu Tormesetik igo ondorengo eskala-aldaketa buruan.</p>\n<h4>Zer begiratu</h4>\n<p>Helmuga baino gehiago, saiatu ibilaldiaren arrastoa nabaritzen. Gorputzak badaki jadanik non estutu ziren kaleak, non zabaldu zen paisaia, non agertu zen harria epel, eta non sentitu zen hezetasuna. Horrelako paseo laburretan memoria fisikoa oso garrantzitsua da.</p>\n<h4>Historia</h4>\n<p>Hiri bat ezagutzea ez da datu multzo bat pilatzea. Batzuetan, ondo aukeratutako ordubete batek askoz gehiago ematen du egun osoko lasterketa turistiko batek baino. Goizeko lehen tarte honek hori egiten du: orientazio emozionala eta materiala ematen dizu.</p>\n<h4>Bitxikeria</h4>\n<p>Paseo on baten neurri ona da amaieran beste erritmo batean ibiltzen jarraitzen baduzu. Hau da, helmugara iritsita ere ez baduzu “bukatu” sentsazioa, baizik eta hiria hobeto irakurtzeko prest zaudela sentitzen baduzu. Hori da gida honen helburua.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez dago hemen azken argazki derrigorrezkorik. Nahiago nuke azken irudia buruan uztea: zubiko isiltasuna, ibaiaren hezetasuna, Casa Lisen arintasuna eta Patio Chicoko harria.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik aurrera, nahi baduzu, gosaria lasai hartu edo kongresuko eguna hasi dezakezu. Baina hiria dagoeneko ez duzu atzokoa bezala ikusiko.</p>",
          "script_path": "../content/eu/dia2_goiza/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada07.mp4",
          "video_exists": true
        }
      ]
    },
    {
      "slug": "dia3_goiza",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Katedrala ulertzeko goizeko paseo luzea",
      "subtitle": "Katedrala plazen, unibertsitatearen eta hiriaren barruan nola aldatzen den ikusteko",
      "duration": "02:20",
      "summary": "Hotelatik abiatu, katedrala hainbat hiri-eszenatokitan irakurri, gosaldu, eta Fonsecan amaitzen den paseo narratiboa.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Colegio Arzobispo Fonseca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9652569,-5.6701508&travelmode=walking&waypoints=40.96445,-5.66859|40.9650282,-5.6640558|40.9629585,-5.6656516|40.961442,-5.667218|40.96098,-5.66575|C.%20San%20Pablo%2C%206%2C%2037001%20Salamanca|40.96114,-5.66702|40.96055,-5.6669|40.96022,-5.66918",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Irteera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Gaur ez dugu katedrala urrunetik bilatuko; hiriaren barruan nola agertzen den ikasiko dugu.",
          "seeing": "Oraingoz ez duzu katedralaren irudi handia aurrean. Hori abantaila da. Hiri arruntetik sartuta, geroago harrizko masa monumentalak askoz indartsuago agertzen dira.",
          "look_now": "Begiratu kaleen erritmoari, itzal luzeari eta harriak oraindik hartu ez duen distira beroari. Geroago tonu horiek guztiek beste zentzu bat hartuko dute.",
          "photo_tip": "Ez egin oraindik gaurko argazki nagusia; gorde lehen irudi indartsua hiri monumentala irekitzen hasten denerako.",
          "hidden_detail": "Hiri historiko bat hobeto irakurtzen da haren ertzetik sartzen zarenean, ez zuzenean postalaren erdian jausita.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Gaur ez dugu katedrala urrunetik bilatuko. Gaur hiriaren barruan nola agertzen den ikasiko dugu. Horregatik, interesgarria da hotelaren inguruko hiri arruntetik abiatzea. Hemen ez dago oraindik postal handirik, eta horrek aukera ematen digu geroago ikusiko dugun harrizko presentzia benetan sentitzeko.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu kaleen erritmoari, itzalei, espaloiei eta batez ere harriaren koloreari. Villamayorreko harria ez da beti berdin agertzen: goizeko lehen argiarekin ezti-tonua hartzen du, eta geroago lauago bihurtzen da. Kolore horrek gidatuko du gaurko paseo osoa.</p>\n<h4>Historia</h4>\n<p>Hall88 ingurua Salamanca garaikidearen ertza da. Hori ez da katedralatik kanpoko zerbait; alderantziz. Hiri historikoaren benetako neurria ulertzeko, haren kanpo-ertza ere sentitu behar da.</p>\n<h4>Bitxikeria</h4>\n<p>Askotan pentsatzen dugu monumentua dela hiriaren hasiera. Baina ia beti lehenago hasten da kontakizuna: nola iristen zaren, zer uzten duzun atzean, eta nola aldatzen den erritmoa oinez zoazen heinean.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez nuke hemen gaurko lehen argazki handia egingo. Hobe da lehen irudi indartsua hiri monumentala irekitzen hasten denerako gordetzea.</p>\n<h4>Nola jarraitu</h4>\n<p>Joan lasai Monterrey aldera. Gaurko lehen zatian hiriaren goiko profila eta haren harrizko hierarkia irakurtzen hasiko gara.</p>",
          "script_path": "../content/eu/dia3_goiza/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada01.mp4",
          "video_exists": false
        },
        {
          "id": 2,
          "time_rel": "00:20",
          "title": "Palacio de Monterrey",
          "short": "Monterrey",
          "lat": 40.96445,
          "lon": -5.66859,
          "blurb": "Katedralara iritsi aurretik, Salamanca zeruaren kontra nola marrazten den ulertzeko lehen pista.",
          "seeing": "Hemen katedrala ez da oraindik protagonista, baina bai hiriaren goiko profila. Monterreyk erakusten du Salamancan boterea sarri gorantz eraiki dela, zerutik irakurtzeko moduan.",
          "look_now": "Begiratu gailurreriari, dorreei eta tximiniei. Pentsatu nola entrenatzen duen zure begirada goiko lerro horrek, gero katedralaren bolumenak hobeto nabaritzeko.",
          "photo_tip": "Urrundu pixka bat eta hartu goiko aldearen erritmoa, ez sarrera bakarrik.",
          "hidden_detail": "Eraikin amaitu gabe batek hiri oso baten iruditeria markatu dezake, eta Monterreyk hori ederki frogatzen du.",
          "image": "../public/images/monterrey.jpg",
          "script_html": "<h3>02 · Palacio de Monterrey</h3>\n<h4>Sarrera</h4>\n<p>Monterreyk ez du katedrala ordezkatzen, baina bai prestatu. Hemen ulertzen hasten da Salamancan boterea sarri gorantz eraiki dela, zeruaren kontra irakurtzeko moduan.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu gailurreriari, dorreei eta tximiniei. Katedrala oraindik ez dago aurrean, baina zure begirada jada goiko lerro horietan entrenatzen ari da. Horrek gero katedralaren bolumenak hobeto irakurtzen lagunduko dizu.</p>\n<h4>Historia</h4>\n<p>Monterrey XVI. mendeko proiektu handiago baten zati amaitua da. Hori bera da haren indarra: amaitu gabe egon arren, hiriaren iruditerian leku handia lortu zuen.</p>\n<h4>Bitxikeria</h4>\n<p>Batzuetan amaitu gabeko eraikinek amaitutakoek baino indar handiagoa dute. Irudimenari lekua uzten diotelako.</p>\n<h4>Non egin argazkia</h4>\n<p>Urrundu pixka bat eta hartu goiko erritmoa. Ez gelditu sarreran bertan.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik Plaza Mayorrera hurbilduko gara. Katedrala ikusi aurretik, haren hiria nolakoa den ulertzea komeni da.</p>",
          "script_path": "../content/eu/dia3_goiza/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96445,-5.66859&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada02.mp4",
          "video_exists": false
        },
        {
          "id": 3,
          "time_rel": "00:34",
          "title": "Plaza Mayor",
          "short": "Plaza",
          "lat": 40.9650282,
          "lon": -5.6640558,
          "blurb": "Hiria barrutik ulertzeko gelarik handiena, katedrala ikusi aurretik espazio urbanoaren neurria ematen duena.",
          "seeing": "Plaza Mayorrek ez dizu katedrala erakusten, baina bai hura posible egiten duen hiria. Espazio publikoa, erritmoa, botere zibila eta eguneroko bizitza hemen antolatzen dira.",
          "look_now": "Gelditu erdian eta egin bira motel bat. Begiratu nola ixten den espazioa zure inguruan, eta nola prestatzen zaituen hiri trinkoago batera sartzeko.",
          "photo_tip": "Erdialdetik Udaletxea edo arku bat marko gisa erabilita, espazioaren eskala erakusten duen argazkia egin.",
          "hidden_detail": "Batzuetan monumentu baten aurreko prestakuntza beste leku batean hasten da; hemen gertatzen da hori.",
          "image": "../public/images/plaza-mayor.jpg",
          "script_html": "<h3>03 · Plaza Mayor</h3>\n<h4>Sarrera</h4>\n<p>Plaza Mayorrek ez dizu katedrala erakusten, baina bai hura posible egiten duen hiria. Espazio publikoa, botere zibila, eguneroko erritmoa eta hiriaren autokonfiantza hemen biltzen dira.</p>\n<h4>Zer begiratu</h4>\n<p>Jarri gutxi gorabehera erdian eta egin bira motel bat. Espazioa nola ixten den sumatuko duzu, baina baita nola uzten dizun ateratzen ere. Plaza honek barrura sartu aurretik hiria neurtzen dizu.</p>\n<h4>Historia</h4>\n<p>XVIII. mendeko plaza barroko hau ez da atseden-leku hutsa. Hiriaren erdiko gela handia da. Horregatik interesatzen zaigu gaur ere: katedrala ez da bakarrik ulertzen, hiri antolatu baten barruan ulertzen da.</p>\n<h4>Bitxikeria</h4>\n<p>Batzuetan monumentu handien aurreko prestakuntza haiek baino urrunago hasten da. Plaza Mayor horietako prestakuntza handietako bat da.</p>\n<h4>Non egin argazkia</h4>\n<p>Erdialdetik Udaletxea edo arku bat marko gisa erabilita, espazioaren eskala erakusten duen argazkia egin.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain Casa de las Conchas aldera joango gara. Hiriaren hizkuntza zibil honetatik nobleziaren eta sinboloaren hizkuntzara pasatuko gara.</p>",
          "script_path": "../content/eu/dia3_goiza/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9650282,-5.6640558&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada03.mp4",
          "video_exists": false
        },
        {
          "id": 4,
          "time_rel": "00:48",
          "title": "Casa de las Conchas",
          "short": "Maskorrak",
          "lat": 40.9629585,
          "lon": -5.6656516,
          "blurb": "Katedralaren inguruko hizkuntza soziala, sinbolikoa eta noblea irakurtzeko leku ezin hobea.",
          "seeing": "Hemen katedrala ez dago aurrean, baina haren hiri bera bai. Maskorrak, atea, leihoak eta pareko masa handiak hiri monumentalaren beste alfabeto bat dira.",
          "look_now": "Begiratu lehenik maskorren erritmoari, gero ateari, eta azkenik pareko eraikin handien presentziari. Hiru geruza horiek batera irakurtzen da lekua.",
          "photo_tip": "Diagonaletik hartu fatxada, errepikapenaren erritmoa eta espazioaren estutasuna nabari daitezen.",
          "hidden_detail": "Hiri bat ez da bere eraikin handiena bakarrik; haren zeinu txiki eta errepikakorrek ere identitatea egiten dute.",
          "image": "../public/images/casa-conchas.jpg",
          "script_html": "<h3>04 · Casa de las Conchas</h3>\n<h4>Sarrera</h4>\n<p>Hemen katedrala ez dago aurrean, baina haren hiri bera bai. Casa de las Conchas da hiri monumentalaren beste alfabetoetako bat: boterea, leinua, erakusgarritasuna eta sinboloa.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu maskorren erritmoari, ateari eta espazioaren estutasunari. Pareko masa handiak ere kontuan hartu. Hemen ez dago objektu isolaturik; elkarrizketa arkitektoniko eta sozial bat dago.</p>\n<h4>Historia</h4>\n<p>XV. mendearen amaierako eta XVI.aren hasierako eraikin hau katedralaren garaikide den hiri-lengoaia baten adibide bikaina da. Oso bestelako hizkuntza erabiltzen du, baina hiri bera osatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Hiri bat ez da bere eraikinik handiena bakarrik. Haren zeinu txiki eta errepikakorrek ere egiten dute identitatea. Hemen maskorrak erritmo sinboliko bat dira.</p>\n<h4>Non egin argazkia</h4>\n<p>Diagonaletik hartu fatxada, errepikapenaren erritmoa eta espazioaren estutasuna nabari daitezen.</p>\n<h4>Nola jarraitu</h4>\n<p>Patio de Escuelaserantz joango gara. Han, katedralaren hiriaren eta jakintzaren hiriaren arteko lotura agerian geratuko da.</p>",
          "script_path": "../content/eu/dia3_goiza/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9629585,-5.6656516&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada04.mp4",
          "video_exists": false
        },
        {
          "id": 5,
          "time_rel": "01:00",
          "title": "Patio de Escuelas",
          "short": "Unibertsitatea",
          "lat": 40.961442,
          "lon": -5.667218,
          "blurb": "Katedralaren hiriaren eta jakintzaren hiriaren arteko elkarrizketa hemen bihurtzen da ageriko.",
          "seeing": "Hemendik unibertsitatea ez da fatxada ospetsu bat bakarrik. Katedralaren auzokoa da, eta bi indar handi horiek elkarri neurria ematen diote.",
          "look_now": "Begiratu patioaren espazioari lehenik, gero fatxadari. Pentsatu katedrala oso gertu dagoela, nahiz eta oraindik ez duzun haren aurrealde handiena osorik aurrean.",
          "photo_tip": "Fray Luis edo patioaren zati bat sartuta, fatxadari arnasa emanez, plano estuegia saihestuz.",
          "hidden_detail": "Salamanca ulertzeko, fedearen eta jakintzaren eraikinak elkarren ondoan nola bizi diren ikusi behar da.",
          "image": "../public/images/universidad.jpg",
          "script_html": "<h3>05 · Patio de Escuelas</h3>\n<h4>Sarrera</h4>\n<p>Hemen Salamancaren oreka handietako bat ageri da: katedrala eta unibertsitatea. Oso gertu daude, elkarren itzalean baina elkarren kontra ez.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu patioaren espazioari lehenik, eta gero fatxadari. Katedrala ez dago osorik aurrean, baina haren presentzia nabaritzen da espazioaren tentsioan eta inguruko harrizko dentsitatean.</p>\n<h4>Historia</h4>\n<p>Salamancako unibertsitatea eta katedral-multzoa ez dira bi mundu paralelo. Mendeetan zehar elkarri lotuta bizi izan dira, eta hiriaren ospea bi ardatz horien inguruan eraiki da neurri handi batean.</p>\n<h4>Bitxikeria</h4>\n<p>Jende asko igelaren bila dator. Ondo dago. Baina hemen are interesgarriagoa da galdetzea zergatik dauden horren gertu bi botere handiak: eliza eta ikasketa.</p>\n<h4>Non egin argazkia</h4>\n<p>Fray Luis edo patioaren zati bat sartuta, fatxadari arnasa emanez, plano estuegia saihestuz.</p>\n<h4>Nola jarraitu</h4>\n<p>Plaza de Anayara hurbilduko gara orain. Han katedralaren aurrealde handia espazio zabal batek nola prestatzen duen ikusiko dugu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.961442,-5.667218&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada05.mp4",
          "video_exists": false
        },
        {
          "id": 6,
          "time_rel": "01:12",
          "title": "Plaza de Anaya",
          "short": "Anaya",
          "lat": 40.96098,
          "lon": -5.66575,
          "blurb": "Orain bai, katedralaren aurrealdea espazio zabal batek prestatuta eta neurtuta agertzen da.",
          "seeing": "Plaza honek katedralaren aurrealdea antolatzen du. Espazioa zabaltzen da, eta eraikinak lehen aldiz aurrez aurreko presentzia handia hartzen du.",
          "look_now": "Jarri plazaren erdiko lerroaren antzeko puntu batean eta begiratu nola prestatzen dizun hutsuneak berak fatxada.",
          "photo_tip": "Ez hartu fatxada soilik; sartu plazaren zati bat, bestela galdu egingo da aurrealdearen eskala.",
          "hidden_detail": "Batzuetan plaza batek azaltzen du eraikin bat bera baino gehiago. Hemen horixe gertatzen da.",
          "image": "../public/images/generated/plaza-anaya.svg",
          "script_html": "<h3>06 · Plaza de Anaya</h3>\n<h4>Sarrera</h4>\n<p>Orain bai, katedralaren aurrealdea aurrez aurre agertzen da. Baina interesgarriena ez da fatxada bera bakarrik; aurretik duen hutsuneak nola prestatzen duen baizik.</p>\n<h4>Zer begiratu</h4>\n<p>Jarri plazaren erdiko lerroaren antzeko puntu batean eta begiratu nola irekitzen den espazioa zure aurrean. Hutsune honek aurrealdeari arnasa ematen dio, eta horregatik sentitzen da hain handia.</p>\n<h4>Historia</h4>\n<p>Katedrala ez dago bakarrik. Plaza batek, jauregi batek eta inguruko ertzek osatzen dute. Horregatik da leku hau hain garrantzitsua: aurrealdea espazio publiko baten bidez eraikitzen da.</p>\n<h4>Bitxikeria</h4>\n<p>Batzuetan plaza batek azaltzen du eraikin bat bera baino gehiago. Hemen horixe gertatzen da: katedralaren tamaina ez dago hormetan bakarrik, aurrean duen hutsunean ere badago.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez hartu fatxada soilik; sartu plazaren zati bat, bestela galdu egingo da aurrealdearen eskala.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain gosariaren geldialdia egingo dugu. Une egokian dator: jada ulertu duzu katedrala hainbat eszenatokitan agertzen dela, eta orain arnasa har dezakezu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96098,-5.66575&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada06.mp4",
          "video_exists": false
        },
        {
          "id": 7,
          "time_rel": "01:24",
          "title": "Dale Café",
          "short": "Gosaria",
          "lat": null,
          "lon": null,
          "blurb": "Gosaria une egokian dator: katedrala hainbat ikuspegitatik irakurri ondoren, hiria barrutik arnasteko.",
          "seeing": "Orain katedralaren irudi handitik atera eta kale biziagora sartzen zara. Horrek ez du kontakizuna hausten; orain arteko ikuspegiak eguneroko Salamancarekin lotzen ditu.",
          "look_now": "Begiratu barruko mugimenduari, katiluen erritmoari eta kalearen esnatzeari. Hartu geldialdi hau benetako trantsizio gisa.",
          "photo_tip": "Barruan, giroa eta katilua; kanpoan, sarrera eta kalearen lehen mugimendua.",
          "hidden_detail": "Lurrean probatuta ondo funtzionatzen duen gosari-leku batek askotan gida baten benetako kalitatea handitzen du.",
          "image": "../public/images/generated/dale-cafe.svg",
          "script_html": "<h3>07 · Dale Café</h3>\n<h4>Sarrera</h4>\n<p>Gosaria ez da parentesi hutsa. Orain arte katedrala plazetan, unibertsitatearen ondoan eta hiriaren barruan irakurri dugu. Hemen, Dale Café-n, irudi horiek pausatu eta eguneroko Salamancarekin lotzen dira.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu barruko mugimenduari, katiluen erritmoari, jendearen sarrera-irteerei eta kalearen esnatzeari. Monumentuz beteriko hiria berriro eguneroko hiri bihurtzen da, eta hori ezinbestekoa da benetan ulertzeko.</p>\n<h4>Historia</h4>\n<p>Geldialdi honen balioa ez dago bakarrik kafean. Zuk probatuta ondo funtzionatzen duen leku batean dago. Horrek gidari baten logikan pisu handia du: errealitateak teoria zuzentzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Batzuetan tokirik onena ez da famatuena, baizik eta ordutegian, erritmoan eta benetako esperientzian ondoen txertatzen dena.</p>\n<h4>Non egin argazkia</h4>\n<p>Barruan, giroa eta katilua; kanpoan, sarrera eta kalearen lehen mugimendua. Ez du zertan gaurko argazkirik ederrena izan.</p>\n<h4>Nola jarraitu</h4>\n<p>Gosaldu ondoren, Patio Chicora itzuliko gara. Begirada pausatuagoa izango duzu, eta katedralaren hazkundea are argiago ikusiko duzu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=C.%20San%20Pablo%2C%206%2C%2037001%20Salamanca&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada07.mp4",
          "video_exists": false
        },
        {
          "id": 8,
          "time_rel": "01:42",
          "title": "Patio Chico",
          "short": "Patio Chico",
          "lat": 40.96114,
          "lon": -5.66702,
          "blurb": "Gosaldu ondoren, katedral zaharra eta berria elkarri lotuta nola hazi ziren berriz ikusteko lekurik onena.",
          "seeing": "Hemen ez duzu fatxada bakarrik ikusten; hazkundearen aztarna ikusten duzu. Pieza zaharra eta pieza berria elkarri itsatsita, ia geologia balira bezala.",
          "look_now": "Begiratu bi bolumenen arteko loturari, ez bakarrik dorre edo kupula bakar bati. Hemen interesgarriena juntura da.",
          "photo_tip": "Behetik pixka bat gora hartu, geruzak elkarren gainean ager daitezen.",
          "hidden_detail": "Katedral berria ez zen zaharra ezabatzeko egin; haren ondoan eta haren gainean ia hazi zen.",
          "image": "../public/images/generated/patio-chico.svg",
          "script_html": "<h3>08 · Patio Chico</h3>\n<h4>Sarrera</h4>\n<p>Gosaldu ondoren hemen itzultzeak badu zentzua. Orain ez zaude presaka, eta katedral zaharra eta berria lotzen dituen juntura askoz argiago irakurtzen da.</p>\n<h4>Zer begiratu</h4>\n<p>Ez bilatu zatirik politena. Begiratu loturari. Nola pilatzen diren hormak, nola elkartzen diren bolumenak, eta nola hazten den eraikin bat aurrekoa ezabatu gabe.</p>\n<h4>Historia</h4>\n<p>Salamancako katedral berria ez zen zaharra botatzeko egin. Haren ondoan, hura zutik mantenduz, handitu zen. Erabaki horrek asko esaten du hiriari buruz.</p>\n<h4>Bitxikeria</h4>\n<p>Eraikuntzaren logika hau ia geologikoa da: geruza berri bat zaharraren gainean, baina hura ezabatu gabe.</p>\n<h4>Non egin argazkia</h4>\n<p>Behetik pixka bat gora hartu, geruzak elkarren gainean ager daitezen. Hemen juntura da protagonista.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik Huerto de Calixto y Melibeara joango gara. Orain katedrala berriro paisaia bihurtzen ikusiko dugu.</p>",
          "script_path": "../content/eu/dia3_goiza/parada08.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96114,-5.66702&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada08.mp4",
          "video_exists": false
        },
        {
          "id": 9,
          "time_rel": "01:54",
          "title": "Calixto eta Melibearen Baratzea",
          "short": "Baratzea",
          "lat": 40.96055,
          "lon": -5.6669,
          "blurb": "Hemen katedrala berriro monumentu hutsa izatetik paisaia eta hiri-ehun bihurtzen da.",
          "seeing": "Landarediaren, hormaren eta hutsuneen artean agertzen denean, katedrala txertatuagoa dirudi. Hori da puntu honen grazia: ez du erakusten bakarrik, baizik eta dosifikatu egiten du.",
          "look_now": "Begiratu hostoen gainetik ageri diren bolumenei. Ez saiatu dena batera harrapatzen; utzi irudia zatika eraikitzen.",
          "photo_tip": "Erabili landaredia aurrealdean eta hartu katedrala haren gainetik agertzen denean.",
          "hidden_detail": "Lorategiak berak baino gehiago, ikuspegia dosifikatzeko moduak egiten du leku hau berezi.",
          "image": "../public/images/generated/huerto-calixto.svg",
          "script_html": "<h3>09 · Calixto eta Melibearen Baratzea</h3>\n<h4>Sarrera</h4>\n<p>Lorategi honek katedrala berriro aldatu egiten du. Orain ez dago aurrealde handi gisa, ezta juntura estu gisa ere. Paisaia eta hiri-ehun gisa agertzen da.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu hostoen gainetik ageri diren bolumenei. Hemen irudia zatika dator, eta horregatik ulertzen da hobeto nola txertatzen den katedrala hirian.</p>\n<h4>Historia</h4>\n<p>Leku hau literaturarekin lotzen da izenagatik, baina gaur guretzat interesgarriena ikuspegia dosifikatzeko modua da. Hemen monumentua ez da objektu bakarra; hiriaren zati bat da.</p>\n<h4>Bitxikeria</h4>\n<p>Lorategiak berak baino gehiago, ikuspegia dosifikatzeko moduak egiten du leku hau berezi.</p>\n<h4>Non egin argazkia</h4>\n<p>Erabili landaredia aurrealdean eta hartu katedrala haren gainetik agertzen denean.</p>\n<h4>Nola jarraitu</h4>\n<p>Azken aurreko geldialdia Casa Lis eta harresiaren ertza izango da. Han ikusiko dugu nola neurtzen diren elkar hiri zaharra eta modernitate arina.</p>",
          "script_path": "../content/eu/dia3_goiza/parada09.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96055,-5.6669&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada09.mp4",
          "video_exists": false
        },
        {
          "id": 10,
          "time_rel": "02:06",
          "title": "Casa Lis eta harresiaren ertza",
          "short": "Casa Lis",
          "lat": 40.96022,
          "lon": -5.66918,
          "blurb": "Ibilaldiaren amaieran, modernitateak eta hiri zaharrak elkar nola neurtzen duten berriz agertzen da.",
          "seeing": "Casa Lisek beira eta burdina jartzen ditu, eta atzean hiri zaharraren logika harrizkoa geratzen da. Horrek azaltzen du Salamanca ez dela garai bakarreko pieza.",
          "look_now": "Begiratu lehenik azal arinari, gero atzeko bolumen zaharragora. Bien arteko tentsioak gaurko paseo osoa laburbiltzen du.",
          "photo_tip": "Jarri Casa Lis apur bat alboan, eta utzi atzean harri zaharragoaren presentzia sartzen.",
          "hidden_detail": "Modernotasunak hemen ez du tradizioa hondatzen; alderantziz, tradizioa are nabarmenago bihurtzen du.",
          "image": "../public/images/generated/casa-lis.svg",
          "script_html": "<h3>10 · Casa Lis eta harresiaren ertza</h3>\n<h4>Sarrera</h4>\n<p>Ibilaldiaren amaieran, modernitateak eta hiri zaharrak elkar nola neurtzen duten berriz agertzen da. Horregatik da puntu hau hain baliotsua amaiera aldera.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lehenik beirari, egiturari eta arintasunari. Gero altxa begirada atzeko logika harrizkora. Bien arteko tentsioak gaurko paseo osoa laburbiltzen du.</p>\n<h4>Historia</h4>\n<p>Casa Lis XX. mendearen hasierako modernismoaren arrastoa da Salamancan. Harresiaren ertzak, berriz, hiri zaharraren logika itxiagoa gogorarazten du. Metro gutxitan bi garai eta bi modu.</p>\n<h4>Bitxikeria</h4>\n<p>Modernotasunak hemen ez du tradizioa hondatzen. Kontrastearen bidez, tradizioa are nabarmenago bihurtzen du.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri Casa Lis apur bat alboan, eta utzi atzean harrizko presentzia zaharragoa sartzen.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik Fonsecaraino azken tarte lasaia baino ez da geratzen. Gaur ikasitakoa lotzeko amaiera egokia da.</p>",
          "script_path": "../content/eu/dia3_goiza/parada10.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96022,-5.66918&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada10.mp4",
          "video_exists": false
        },
        {
          "id": 11,
          "time_rel": "02:20",
          "title": "Colegio Arzobispo Fonseca",
          "short": "Fonseca",
          "lat": 40.9652569,
          "lon": -5.6701508,
          "blurb": "Paseoa hemen ixten da, katedrala ulertzetik hiri akademiko eta instituzionalera berriz itzulita.",
          "seeing": "Fonsecan amaitzeak zentzua du. Paseo osoan zehar katedrala, unibertsitatea, plaza eta hiriaren beste hizkuntza batzuk lotu ditugu, eta hemen berriz ere sare hori eguneroko erabileran biltzen da.",
          "look_now": "Begiratu atariari eta fatxadaren lasaitasunari. Ez du katedralaren dramatismoa, baina bai hiriaren beste botere isilago baten presentzia.",
          "photo_tip": "Kalearen beste aldetik, presarik gabe, fatxada osoa eta sarrerako lasaitasuna hartzeko.",
          "hidden_detail": "Ibilbidea ez da katedralaren aurrean amaitzen, baizik eta hura posible egin zuen hiri-sarearen beste pieza batean.",
          "image": "../public/images/fonseca.jpg",
          "script_html": "<h3>11 · Colegio Arzobispo Fonseca</h3>\n<h4>Sarrera</h4>\n<p>Eta hemen ixten da zirkulua. Katedrala ulertzeko hasi dugun paseoa hura posible egin zuen hiri-sarearen beste pieza batean amaitzen da: ikasketa, erakundea eta eguneroko erabilera.</p>\n<h4>Zer begiratu</h4>\n<p>Fonsecak ez du katedralaren dramatismoa, baina badu beste indar bat: neurria, isiltasuna eta iraupena. Hemen ulertzen da Salamanca ez dela eraikin ospetsuen segida bat bakarrik.</p>\n<h4>Historia</h4>\n<p>XVI. mendearen hasieran sortutako ikastetxe honek erakusten du unibertsitate-hiriaren eta eliza-hiriaren arteko lotura ez dela ideia abstraktua. Harrian eta erabileran dago.</p>\n<h4>Bitxikeria</h4>\n<p>Ibilbide on baten seinaleetako bat da amaieran hiri bera desberdin ikusten baduzu. Ez du zertan monumentu gehiago erakutsi; nahikoa da loturak ikasi izana.</p>\n<h4>Non egin argazkia</h4>\n<p>Kalearen beste aldetik, presarik gabe, fatxada osoa eta sarrerako lasaitasuna hartzeko.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik kongresura joan zaitezke zuzenean. Gaurko ibilbideak bere lana egina du: Salamanca irudi solteetan baino, loturen bidez irakurtzen laguntzea.</p>",
          "script_path": "../content/eu/dia3_goiza/parada11.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9652569,-5.6701508&travelmode=walking",
          "video_url": "../public/media/dia3_goiza/parada11.mp4",
          "video_exists": false
        }
      ]
    }
  ]
};
