window.GUIDE_DATA = {
  "app": {
    "title": "Salamanca Guide",
    "tagline": "Google Maps-ek oinak gidatzen ditu. PWAk begirada.",
    "defaultRoute": "dia2_goiza"
  },
  "routes": [
    {
      "slug": "dia1",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Lehen arratsaldea: hotelatik Fonsecaraino",
      "subtitle": "Kafea, harri urreztatua eta lehen orientazioa presarik gabe",
      "duration": "01:45",
      "summary": "Kongresuko harrerara iritsi aurretik, hiria lasai irakurtzen hasteko ibilbidea.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Colegio Arzobispo Fonseca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9652569,-5.6701508&travelmode=walking&waypoints=40.9653616,-5.6636406|40.9650282,-5.6640558|40.9629585,-5.6656516|40.961442,-5.667218|40.96445,-5.66859",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Irteera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Hiri garaikidetik alde zaharrerako trantsizio lasaia.",
          "photo_tip": "Ez gastatu lehen argazkia hemen; gorde lehen benetako koadroa erdigunerako.",
          "hidden_detail": "Hall88 ingurua muga atsegina da Salamanca egunerokoaren eta monumentalenaren artean.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Irteera: Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Lasai hasi. Gaur arratsaldean ez dugu “Salamanca egin” nahi: hiria irakurtzen ikasi besterik ez dugu egingo. Unibertsitate-auzo moderno batetik abiatu, erdiguneko harri urrezturantz joan eta harrera hasten den leku berean amaituko dugu.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu nola aldatzen den hiria alde zaharrera hurbiltzean: etorbideak estutu egiten dira, trafikoa gutxitzen da eta hareharria fatxadetan nagusitzen hasten da.</p>\n<h4>Historia</h4>\n<p>Hotela Miguel de Unamuno campusaren ondoan dago, autobus-geltokiaren aurrean. Eguneroko Salamanca eta Salamanca monumentala bereizten dituen muga ona da.</p>\n<h4>Bitxikeria</h4>\n<p>Villamayorreko harria ia krema kolorekoa dirudi egunez, baina albo-argiarekin ezti kolorekoa bihurtzen da. Kolore-aldaketa hori izango da paseoaren hari bisuala.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez da beharrezkoa hotela fotografiatzea. Gorde lehen irudia Plaza Mayor agertzen denerako: kontrasteak hobeto kontatuko du iritsiera.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Peña de Francia kaletik eta jarraitu erdigunerantz. Lehen helburua Café Novelty da, hogei minutu ingurura. Gurutza itzazu etorbideak seinaleztatutako pasabideetatik.</p>",
          "script_path": "../content/eu/dia1/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia1/parada01.mp4",
          "video_exists": true
        },
        {
          "id": 2,
          "time_rel": "00:24",
          "title": "Café Novelty",
          "short": "Kafea",
          "lat": 40.9653616,
          "lon": -5.6636406,
          "blurb": "Lehen atsedenaldiak paseoari erritmo egokia ematen dio.",
          "photo_tip": "Arkupeen azpitik, diagonalean, plazaren lehen markoa hartu.",
          "hidden_detail": "Kafetegiaren memoria literarioak plazaren ikuspegia baino gehiago ematen du.",
          "image": "../public/images/cafe-novelty.jpg",
          "script_html": "<h3>02 · Café Novelty</h3>\n<h4>Sarrera</h4>\n<p>Atsedenaldira une egokian iritsi zara, eta hori zen asmoa. Sartu Noveltyn 17:23 eta 17:25 artean, eta gorde hogei minutu inguru kafearentzat.</p>\n<h4>Zer begiratu</h4>\n<p>Bilatu hizketarako kafetegi-giroa, ez bakarrik Plazaren ikuspegia. Barruan Gonzalo Torrente Ballesterren eskultura dago, beste bezero bat balitz bezala eserita.</p>\n<h4>Historia</h4>\n<p>Novelty 1905ean ireki zuten, eta Salamancako kafetegirik zaharrena dela aldarrikatzen du. Haren mahaietatik hiriko bizitza kulturalaren zati handi bat igaro zen. Egungo lokalak memoria hori gordetzen du, denborarekin aldatu bada ere.</p>\n<h4>Bitxikeria</h4>\n<p>Torrente Ballesterrek hiri imajinarioei buruz idatzi zuen, baina hemen kafetegiko bizilagun iraunkor bihurtu zen. Tokirik badago, haren ondoan esertzea da geldialdi honetako erritu txikia.</p>\n<h4>Non egin argazkia</h4>\n<p>Egin barruko argazki bat eskulturarantz, beste bezeroei trabarik egin gabe. Kanpoan, jarri arkupeen azpian eta atera Plazaren argazkia diagonalean, arkuekin marko gisa. Gutxi gorabeherako orientazioa: ekialde-ipar-ekialdea.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Noveltytik Plaza Mayorreko erdialderantz. Hurrengo geldialdia minutu bat baino gutxiagora dago: ez hasi oraindik presaka; lehenik begiratu espazio osoa.</p>",
          "script_path": "../content/eu/dia1/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9653616,-5.6636406&travelmode=walking",
          "video_url": "../public/media/dia1/parada02.mp4",
          "video_exists": true
        },
        {
          "id": 3,
          "time_rel": "00:45",
          "title": "Plaza Mayor",
          "short": "Plaza",
          "lat": 40.9650282,
          "lon": -5.6640558,
          "blurb": "Ez helmuga gisa, sarrera handi gisa irakurtzeko plaza.",
          "photo_tip": "Erdialdean gelditu eta udaletxerantz zuzendu marko zabala egiteko.",
          "hidden_detail": "Laukia oso orekatua da, baina ez da guztiz simetrikoa.",
          "image": "../public/images/plaza-mayor.jpg",
          "script_html": "<h3>03 · Plaza Mayor</h3>\n<h4>Sarrera</h4>\n<p>Oraingoan Plaza Mayor ez da eguneko amaiera handia, sarrerako atea baizik. Gelditu minutu batzuk bakarrik: bihar beste argi eta beste erritmo batekin itzul zaitezke.</p>\n<h4>Zer begiratu</h4>\n<p>Jarri gutxi gorabehera erdian eta egin bira poliki. Plaza erabat erregularra dirudi, baina pabiloi bakoitzak bere eginkizuna du eta Udaletxeko kanpai-hormak horizontala hausten du.</p>\n<h4>Historia</h4>\n<p>Plaza barrokoa XVIII. mendean eraiki zen. Alberto de Churriguerak abiatu zuen proiektua, eta Andrés García de Quiñonesek osatu zuen multzoaren zati handi bat. Arkuetako medailoiek pertsonaien galeria bihurtzen dute arkupeetako ibilaldia.</p>\n<h4>Bitxikeria</h4>\n<p>Zenbatu aldeak begiradaz: karratu perfektu baten inpresioa ematen du, oinplano erreala hala ez izan arren. Arkitekturak erritmoaren eta errepikapenaren bidez zuzentzen du gure pertzepzioa.</p>\n<h4>Non egin argazkia</h4>\n<p>Erdigunetik, enkoadratu Udaletxea bertikalean; argazki lasaiago baterako, erabili arkupeetako arkuetako bat marko gisa. Ordu honetan argia gogorra izan daiteke: neurtu harrirako eta utzi zerua pixka bat argiago.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten plazatik hego-mendebaldeko irteeratik eta hartu Rúa Mayor. Bost minutu inguruan aurrez aurre agertuko dira Casa de las Conchas eta Clerecía.</p>",
          "script_path": "../content/eu/dia1/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9650282,-5.6640558&travelmode=walking",
          "video_url": "../public/media/dia1/parada03.mp4",
          "video_exists": true
        },
        {
          "id": 4,
          "time_rel": "00:57",
          "title": "Casa de las Conchas",
          "short": "Maskorrak",
          "lat": 40.9629585,
          "lon": -5.6656516,
          "blurb": "Fatxada bakarra eta Clerecíarekin duen elkarrizketa bisuala.",
          "photo_tip": "Clerecíaren aldetik, diagonalean, maskorren erritmoa hobeto ikusten da.",
          "hidden_detail": "Fatxada osoa ez da apaindura hutsa; botere sinbolikoaren erakusketa ere bada.",
          "image": "../public/images/casa-conchas.jpg",
          "script_html": "<h3>04 · Casa de las Conchas</h3>\n<h4>Sarrera</h4>\n<p>Hemen Salamancak liburu eta igarkizun izatera jokatzen du. Ez da barrura sartu behar: fatxadak berak kontatzen du leinuen, sinboloen eta prestigioaren historia.</p>\n<h4>Zer begiratu</h4>\n<p>Ez begiratu maskorrei bakarrik. Erreparatu leihoetako saretei, ateari eta aurrez aurre dauden Clerecíako dorreekin duen elkarrizketari. Espazioa estua da eta gora begiratzera behartzen du.</p>\n<h4>Historia</h4>\n<p>Jauregia XV. mendearen amaiera eta XVI.aren hasiera artean eraiki zuten Rodrigo Arias Maldonadorentzat. Maskorrak Santiago Ordenarekin lotzen dira, baina baita Pimentel familiaren ikurrarekin ere.</p>\n<h4>Bitxikeria</h4>\n<p>Kondairak dio maskorretako batek altxor bat ezkutatzen duela. Istorio ezin hobea da fatxada errepikakor baterako: dena berdina dirudienean, salbuespena bilatzen hasten gara.</p>\n<h4>Non egin argazkia</h4>\n<p>Gurutzatu Clerecíarantz eta erabili angelu zabal samarra. Maskorren erritmoa harrapatzeko, atera argazkia diagonalean fatxadaren iparraldeko muturretik. Orientazioa: mendebalde-hego-mendebaldea.</p>\n<h4>Nola jarraitu</h4>\n<p>Jarraitu Libreros kaletik eta biratu Patio de Escuelaserantz. Lau minutu inguruko bidea da oinez. Han bilatu Unibertsitatearen fatxada historikoa eta Fray Luis de Leónen estatua.</p>",
          "script_path": "../content/eu/dia1/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9629585,-5.6656516&travelmode=walking",
          "video_url": "../public/media/dia1/parada04.mp4",
          "video_exists": true
        },
        {
          "id": 5,
          "time_rel": "01:10",
          "title": "Unibertsitatea eta Patio de Escuelas",
          "short": "Unibertsitatea",
          "lat": 40.961442,
          "lon": -5.667218,
          "blurb": "Ikur handiak lehen begiratuan baino lasaiago irakurtzeko tokia.",
          "photo_tip": "Fray Luis lehen planoan utzi eta fatxada pixka bat alboratuta hartu.",
          "hidden_detail": "Jende gehiena igelaren bila hasten da eta eskulturaren kontakizun osoa galtzen du.",
          "image": "../public/images/universidad.jpg",
          "script_html": "<h3>05 · Unibertsitatea, Patio de Escuelas</h3>\n<h4>Sarrera</h4>\n<p>Patio hau eszenatoki txiki bat da. Jarri Fray Luis de León ondoan eta utzi estatuak nora begiratu esaten: fatxada ia harrizko orrialde bat da.</p>\n<h4>Zer begiratu</h4>\n<p>Igo begirada fatxadan behetik gora. Lehenik Errege Katolikoak, gero armarrien eta medailoien eremua, eta azkenik zatirik sinbolikoena. Ez bihurtu igela bilaketa urduri batean; multzoak jokoak baino gehiago balio du.</p>\n<h4>Historia</h4>\n<p>Salamancako Unibertsitatearen jatorria 1218ra doa. Fatxada plateresko ospetsua geroagokoa da, XVI. mendearen hasierakoa, eta boterea, ezagutza eta monarkia programa bisual beraren zati gisa aurkezten ditu.</p>\n<h4>Bitxikeria</h4>\n<p>Igela garezur baten gainean dago. Ikasleen tradizioak zorte akademikoa agintzen dio aurkitzen duenari, baina agian zentzuzkoena beste ikasgai bat da: arreta handiz begiratzeak beti laguntzen du azterketa batean.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri Fray Luisen atzean edo pixka bat albo batean haren silueta eta fatxada batera sartzeko. Orientazioa: mendebaldea. Erliebeetarako, erabili zooma eta saihestu mugikorra gehiegi makurtzea.</p>\n<h4>Nola jarraitu</h4>\n<p>Irten Patio de Escuelasetik Compañía kalerantz eta egin aurrera ipar-mendebaldera. Ibilbideak Monterrey jauregira eramango zaitu hamar minutu inguruan; Fonsecaren aurreko argazki-geldialdi laburra da.</p>",
          "script_path": "../content/eu/dia1/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.961442,-5.667218&travelmode=walking",
          "video_url": "../public/media/dia1/parada05.mp4",
          "video_exists": true
        },
        {
          "id": 6,
          "time_rel": "01:28",
          "title": "Palacio de Monterrey",
          "short": "Monterrey",
          "lat": 40.96445,
          "lon": -5.66859,
          "blurb": "Geldialdi labur baina oso fotogenikoa.",
          "photo_tip": "Hobe diagonalean, dorreak eta gailurreria batera sartzeko.",
          "hidden_detail": "Eraikin amaitu gabe batek estilo oso baten iruditeria markatu zuen.",
          "image": "../public/images/monterrey.jpg",
          "script_html": "<h3>06 · Monterrey jauregia</h3>\n<h4>Sarrera</h4>\n<p>Hau bost minutuko etenaldia da, ez bisita osoa. Jauregiak unibertsitate-gunearen eta Fonsecaren arteko giltza-lana egiten du.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu zeruaren kontra moztutako gailurreria, dorreak eta tximiniak. Goiko aldeak hainbesteko nortasuna du, non beste hiri batzuetako eraikinek imitatutako estilo bati izena eman zion.</p>\n<h4>Historia</h4>\n<p>Jauregia 1539an hasi ziren eraikitzen Monterreyko kondearentzat. Jatorrizko proiektuaren zati bat baino ez zen gauzatu, baina nahikoa izan zen Espainiako arkitektura errenazentistaren erreferente bihurtzeko.</p>\n<h4>Bitxikeria</h4>\n<p>Gaur eraikin osoa dirudiena, egiaz, asmo askoz handiago baten zati bat zen. Batzuetan eragin handiena duen arkitektura amaitu gabeko proiektu batetik sortzen da.</p>\n<h4>Non egin argazkia</h4>\n<p>Plazatik, urrundu hego-ekialderantz dorre bat eta goiko galeria diagonalean sartzeko. Ordu honetan saiatu argiak harria laztan dezan. Gutxi gorabeherako orientazioa: ipar-mendebaldea.</p>\n<h4>Nola jarraitu</h4>\n<p>Hartu Bordadores kalea eta jarraitu Fonsecarantz. Zortzi minutu inguru falta dira. Ez geratu gehiegi: helburua 18:40 eta 18:45 artean atean egotea da.</p>",
          "script_path": "../content/eu/dia1/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96445,-5.66859&travelmode=walking",
          "video_url": "../public/media/dia1/parada06.mp4",
          "video_exists": true
        },
        {
          "id": 7,
          "time_rel": "01:40",
          "title": "Colegio Arzobispo Fonseca",
          "short": "Fonseca",
          "lat": 40.9652569,
          "lon": -5.6701508,
          "blurb": "Harrerara iritsi aurretik, atariaren lasaitasuna aprobetxatzeko azken pausa.",
          "photo_tip": "Kalearen beste aldetik, fatxada osorik eta presarik gabe.",
          "hidden_detail": "Gaur egungo erabilera kulturala eta unibertsitarioa jatorri errenazentistarekin lotuta jarraitzen du.",
          "image": "../public/images/fonseca.jpg",
          "script_html": "<h3>07 · Arzobispo Fonseca ikastetxea</h3>\n<h4>Sarrera</h4>\n<p>Ibilbidea hemen amaitzen da, arratsaldeko beste zati bat hasten den une berean. Bi ordu baino gutxiagoan Salamanca garaikidetik haren antzinako ikastetxe nagusietako batera iritsi zara.</p>\n<h4>Zer begiratu</h4>\n<p>Sartu aurretik, begiratu fatxada eta ataria. Harrerak patiora pasatzeko aukera ematen badu, utzi audiogida pausatuta: espazio hori azalpenik gabe ikustea merezi du.</p>\n<h4>Historia</h4>\n<p>Alonso de Fonsecak sortu zuen ikastetxea, eta lanak 1519an hasi ziren. Hasieran irakaskuntzarako eta egoitzarako izan zen, eta gaur egun unibertsitate-ostatua, kultur ekitaldiak eta topaketa instituzionalak hartzen ditu.</p>\n<h4>Bitxikeria</h4>\n<p>Ondorengo mendeetan erakunde honi lotutako ikasle katoliko irlandarrengatik, Irlandarren Ikastetxea izenez ere ezagutu zen.</p>\n<h4>Non egin argazkia</h4>\n<p>Kontrako espaloitik, enkoadratu ataria aurrez aurre. Harrerara jendea iristen ari bada, albo pixka bateko hartualdi bat diskretuagoa izango da eta eraikinaren bolumena hobeto erakutsiko du. Ibilbide honetarako ordurik onena: 18:40–18:45.</p>\n<h4>Nola jarraitu</h4>\n<p>Sartu harrerara. Aplikazioaren ibilbidea hemen amaitzen da; ez du hotelerako itzulera automatikorik proposatzen. Bidaiaren aurretik komeni da kongresuko programan baieztatzea harrera benetan Fonseca kalea 4an dela.</p>",
          "script_path": "../content/eu/dia1/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9652569,-5.6701508&travelmode=walking",
          "video_url": "../public/media/dia1/parada07.mp4",
          "video_exists": true
        }
      ]
    },
    {
      "slug": "dia2_goiza",
      "city": "Salamanca",
      "lang": "eu",
      "title": "Goizeko paseo lasaia Salamancan",
      "subtitle": "Egunsentiko argia, ibaia eta harrizko hiriaren lehen isiltasuna",
      "duration": "01:00",
      "summary": "Hotelatik abiatu, Tormesera jaitsi eta alde zaharrera igo, turista gutxien dagoenean.",
      "start_label": "Zenit Hall88 Studios Salamanca",
      "end_label": "Zenit Hall88 Studios Salamanca",
      "route_maps_url": "https://www.google.com/maps/dir/?api=1&origin=40.9702112,-5.6766756&destination=40.9702112,-5.6766756&travelmode=walking&waypoints=40.96229,-5.67147|40.9609,-5.6699|40.96022,-5.66918|40.96055,-5.6669|40.96114,-5.66702",
      "stops": [
        {
          "id": 1,
          "time_rel": "00:00",
          "title": "Zenit Hall88",
          "short": "Hotela",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Irteera lasaia, lo dagoen hiria atzean utzi gabe.",
          "photo_tip": "Hemen ez dago argazki handirik; onena lehen argia gordetzea da.",
          "hidden_detail": "Eguneko erritmoa hasi aurreko minutuak dira, eta hori da ibilbide honen benetako luxua.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>01 · Zenit Hall88</h3>\n<h4>Sarrera</h4>\n<p>Hau ez da gaurko “ibilaldi nagusia”, eta horregatik da hain baliotsua. Goizeko paseo honek ez du monumentu guztiak kateatu nahi; zure begirada egokitu nahi du. Hemen, hotelaren aurrean, hiriak oraindik ez du bere eguneroko zarata hartu. Autobus-geltokiaren ingurua esnatzen hasiko da laster, baina oraindik badago tarte labur bat non Salamanca ia atariko arnasa balitz bezala sentitzen den.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lehenengo minutuetan argiak nola lantzen dituen fatxaden tonuak. Villamayorreko harria ez da urre kolorekoa berez: eguzki baxuarekin eta aireko hezetasunarekin eraikitzen da kolore hori. Hori da paseo honetako hari ezkutua. Hemendik behera joango gara, baina egia esan gorantz hasiko da zure irakurketa: gero eta hobeto ulertuko duzu hiria zer materialekin eta zer erritmorekin egin den.</p>\n<h4>Historia</h4>\n<p>Hall88 ingurua Salamanca garaikidearen ertza da, unibertsitate-bizitzaren eta eguneroko logistikaren artean. Horrek abantaila bat ematen dio hasiera honi: alde zaharrera ez zara bat-batean iristen, baizik eta trantsizio baten bidez. Hiri historikoetan hori askotan galtzen dugu, zuzenean postalaren erdira salto egiten dugulako.</p>\n<h4>Bitxikeria</h4>\n<p>Harrizko hiri handi askotan bezala, lehen inpresioa ez da beti eraikin ospetsu batek ematen; askotan kalearen kalitateak ematen du. Oinez zoazenean sumatzen duzu zein den espaloien, zuhaitzen, itzalen eta fatxaden arteko oreka. Horregatik komeni da lehen minutuetan ez presaka ateratzea.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez nuke hemen argazki nagusia egingo. Gorde lehen irudi benetan ona zubirako edo ibairako. Hasiera honek balio handiagoa du erritmoa markatzeko, ez albumaren lehen orria betetzeko.</p>\n<h4>Nola jarraitu</h4>\n<p>Joan lasai Puente Romanorantz. Ez pentsatu helmugan bakarrik: jaitsiera bera da gaurko lehen prestaketa. Handik aurrera, Salamanca monumentala ez duzu aurrez aurre soilik ikusiko; urrutitik irakurtzen hasiko zara.</p>",
          "script_path": "../content/eu/dia2_goiza/parada01.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada01.mp4",
          "video_exists": true
        },
        {
          "id": 2,
          "time_rel": "00:12",
          "title": "Puente Romano",
          "short": "Zubia",
          "lat": 40.96229,
          "lon": -5.67147,
          "blurb": "Zubi zaharrean, hiria atzealde bihurtzen da eta paisaia nagusi.",
          "photo_tip": "Zubiaren erdian baino, zertxobait albo batera, katedralak eta ibai-lerroa batera hartzeko.",
          "hidden_detail": "Gaur ikusten dena ez da erromatar obra osoa, baina ideia erromatarra bai: igarobide sendoa, uraren gainean.",
          "image": "../public/images/generated/puente-romano.svg",
          "script_html": "<h3>02 · Puente Romano</h3>\n<h4>Sarrera</h4>\n<p>Hemen hasten da benetako goizeko magia. Zubira iristean, hiriak atzera egiten du apur bat eta paisaiak hartzen du protagonismoa. Horregatik gustatzen zait geldialdi hau ibilaldiaren hasieran jartzea: Salamanca lehenik silueta gisa ikusten duzu, eta geroago bakarrik xehetasun gisa.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu nola antolatzen diren planoak: behean Tormes, erdian zubiaren arkuen erritmoa, eta atzean dorreak, kupulak eta harlandua. Goizeko lehen argiarekin kontrastea oso leuna izan ohi da, eta horrek aukera ematen du hiriaren masa ulertzeko, ez bakarrik bere apaingarriak.</p>\n<h4>Historia</h4>\n<p>Puente Romano deitzen diogu, eta izena egokia da neurri batean, baina hemen interesgarriena ez da “zenbat geratzen den jatorrizkotik” galdera hutsa. Garrantzitsuena da mendeetan zehar ibaiaren pasabide nagusiaren ideia hemen iraun duela. Zubiak ez du soilik ertzak lotzen; Salamanca nola sartzen eta irteten zen kontatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Zubi zaharrek badute ia beti zerbait zientifikotik. Arkuen forma, karga banaketa, uraren presioa, materialaren higadura… dena dago ikusgai, nahiz eta oinez zoazen bitartean ez pentsatu formula bakar batean ere. Ingeniaritza ona askotan ikusezina da, eta hemen hori ederki antzematen da.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez gelditu arkuen erdiko simetriaren bila bakarrik. Mugitu apur bat, eta bilatu ikuspegi apur bat zeiharra: horrela hiriaren profila, zubiaren lerroa eta ibaiaren mugimendua batera sartzen dira. Goizeko argiak bolumenak hobeto modelatzen ditu horrela.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain ibaiertzera jaitsiko gara. Hori da hurrengo geldialdiaren gakoa: zubia egitura bezala ikusi dugu; handik gutxira, ura eta hezetasuna hiriaren materialekin nola elkartzen diren ikusiko dugu.</p>",
          "script_path": "../content/eu/dia2_goiza/parada02.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96229,-5.67147&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada02.mp4",
          "video_exists": true
        },
        {
          "id": 3,
          "time_rel": "00:22",
          "title": "Tormes ibaiertza",
          "short": "Ibaia",
          "lat": 40.9609,
          "lon": -5.6699,
          "blurb": "Hemen Salamanca ez da monumentu multzo bat bakarrik; uraren ertzeko hiri bat ere bada.",
          "photo_tip": "Ura bare badago, bilatu islak; haizerik badago, landarediaren eta harrien arteko kontrastea.",
          "hidden_detail": "Egunsentiko argi zeharkakoak Villamayorreko harria eta ibaiaren hezetasuna tonu oso desberdinetan banatzen ditu.",
          "image": "../public/images/generated/ribera-tormes.svg",
          "script_html": "<h3>03 · Tormes ibaiertza</h3>\n<h4>Sarrera</h4>\n<p>Ibaian behera edo haren ertzean zaudenean, Salamanca ez da hain akademikoa, ez hain “postalekoa”. Hemen hiria arnasten da beste modu batean. Uraren presentziak tenperatura aldatzen du, soinua aldatzen du, eta baita argiaren kalitatea ere.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu lurzoruaren hezetasunari, landarediaren koloreari eta atzean ageri diren harrizko hormei. Egunsentian oso nabarmena da nola banatzen diren tonuak: harria epelagoa dirudi, ura hotzagoa, eta bien arteko trantsizioa oso sotila da. Hori ez da poesia bakarrik; gainazal bakoitzak argia eta beroa modu desberdinean xurgatzen dituelako gertatzen da.</p>\n<h4>Historia</h4>\n<p>Tormesek Salamanca hornitu, babestu eta mugatu egin du aldi berean. Ibaiak hiriari bizkarra ematen diola esaten da askotan, baina hori egia erdia da. Historikoki, ibaiaren ertza funtzionala zen: garraioa, sarrerak, irteerak, laborantza txikiak, eta hezetasunarekiko etengabeko negoziazioa.</p>\n<h4>Bitxikeria</h4>\n<p>Higadurak hemen erakusten du bere lanik isilena. Harri guztiak ez dira berdin zahartzen, eta ez dute guztiok ura berdin jasaten. Villamayorreko harria ederra da, baina material biguna ere bada; horregatik, uraren, haizearen eta kutsaduraren aurrean berehala irakurtzen dira aldaketak.</p>\n<h4>Non egin argazkia</h4>\n<p>Ura bare badago, islen bila joan. Haize pixka bat badabil, orduan hobe da ertzeko landaredia lehen plano gisa erabiltzea. Bi kasuetan, ez saiatu dena sartzen: hobe da zati bat ondo irakurtzea plano handi bat gaizki egitea baino.</p>\n<h4>Nola jarraitu</h4>\n<p>Handik gutxira Casa Lis agertuko zaigu. Ibaiko lasaitasun honetatik modernismo arin batera pasatuko gara. Kontraste hori da geldialdi hurrengoaren xarma.</p>",
          "script_path": "../content/eu/dia2_goiza/parada03.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9609,-5.6699&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada03.mp4",
          "video_exists": true
        },
        {
          "id": 4,
          "time_rel": "00:32",
          "title": "Casa Lis (kanpotik)",
          "short": "Casa Lis",
          "lat": 40.96022,
          "lon": -5.66918,
          "blurb": "Modernismo arina, harrizko hiri klasikoaren alboan.",
          "photo_tip": "Kristal eta burdin egitura albo batetik hartu, kurbadurak hobeto nabaritzeko.",
          "hidden_detail": "Casa Lisek erakusten du Salamanca ez dela erromanikoa, gotikoa edo platereskoa bakarrik; XX. mendearen hasierak ere hemen utzi zuen arrastoa.",
          "image": "../public/images/generated/casa-lis.svg",
          "script_html": "<h3>04 · Casa Lis (kanpotik)</h3>\n<h4>Sarrera</h4>\n<p>Casa Lisek beti ematen du sorpresa txiki bat. Salamanca hain sendoa, hain harrizkoa eta hain klasikoa iruditzen zaigunean, bat-batean kristala, burdina eta kurba agertzen dira. Horregatik da interesgarria kanpotik ere: ez dugu barrura sartu behar eraikinak zer esan nahi duen ulertzeko.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu fatxadaren arintasunari. Ez da katedral baten masa, ez jauregi baten horma lodia. Hemen azal bat dago, ia pabiloi moduko zerbait, eta horrek inguruko eraikinekin duen kontrastea oso adierazgarria da. Material gardena eta egitura metalikoa ikusita, berehala sumatzen da beste garai batean gaudela.</p>\n<h4>Historia</h4>\n<p>Casa Lis XX. mendearen hasierako modernismoaren arrastoa da Salamancan. Horrek ez du esan nahi hiria bat-batean modernista bihurtu zenik; alderantziz, hain zuzen. Horregatik da hain deigarria: tradizio sendo baten alboan, beste hizkuntza arkitektoniko batek bere lekua bilatzen du.</p>\n<h4>Bitxikeria</h4>\n<p>Askotan, hiri historikoetan modernotasuna “istripu” bat balitz bezala ikusten dugu. Baina askotan modernotasuna da hiriari arnasa ematen diona, kontrastea sortzen duena. Casa Lisek hori egiten du: Salamanca harrizkoa are gehiago nabarmentzen du, hain zuzen arinagoa delako.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez saiatu eraikina aurrez aurre eta lauki perfektuan harrapatzen. Hobe albo batetik, egitura kurboak eta beiraren geruzak irakurtzeko. Horrela hobeto ulertzen da ez dela fatxada apaindu bat bakarrik, baizik eta sistema estetiko oso bat.</p>\n<h4>Nola jarraitu</h4>\n<p>Orain Calixto eta Melibearen Baratzerantz igoko gara. Casa Lisen gardentasunetik landarediaren eta harresiaren arteko tarte intimora pasatuko gara. Oso aldaketa atsegina da oinez.</p>",
          "script_path": "../content/eu/dia2_goiza/parada04.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96022,-5.66918&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada04.mp4",
          "video_exists": true
        },
        {
          "id": 5,
          "time_rel": "00:40",
          "title": "Calixto eta Melibearen Baratzea",
          "short": "Baratzea",
          "lat": 40.96055,
          "lon": -5.6669,
          "blurb": "Hemen hiria itxiago sentitzen da, baina ikuspegia zabaldu egiten da.",
          "photo_tip": "Baratze barrutik hartu katedralen bolumena, landaredia aurrealdean utzita.",
          "hidden_detail": "Landareen artean dagoen intimitateak La Celestinaren iruditeria elikatzen du, nahiz eta lorategia gaur egunekoa izan neurri handi batean.",
          "image": "../public/images/generated/huerto-calixto.svg",
          "script_html": "<h3>05 · Calixto eta Melibearen Baratzea</h3>\n<h4>Sarrera</h4>\n<p>Baratze honetara iristean, paseoaren tonuak berriro aldatzen dira. Ibaiaren zabaltasunetik eta Casa Lisen arintasunetik, espazio itxiago baina intimoago batera sartzen zara. Hemen Salamanca ez da soilik ikusgarria; kontenplatiboa ere bada.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu landarediaren eta harrizko bolumenen arteko harremanari. Baratzeak ikuspegia iragazten du: ez dizu hiria kolpe bakarrean ematen, hostoen, hormen eta irekiduren artean dosifikatzen dizu. Horregatik funtzionatzen du hain ondo goizean; jende gutxi dagoenean, espazioak bere erritmo propioa mantentzen du.</p>\n<h4>Historia</h4>\n<p>Izenak zuzenean La Celestinaren iruditeriara garamatza. Hori da, neurri batean, espazio honen xarma: benetako paisaia eta literatura memorian nahasten dira. Lorategia gaur ezagutzen dugun moduan ez da Erdi Aroko eszenografia gordina, noski, baina izenak eta kokapenak fikzioaren geruza bat eransten diote.</p>\n<h4>Bitxikeria</h4>\n<p>Baratzeek ere badute zientziatik. Itzalak, orientazioak eta hezetasunak erabakitzen dute zer landarek funtzionatzen duen hobeto eta nola eusten zaion udako beroari. Hiri historiko batean lorategi txiki batek mikroklima propioa sor dezake, eta goizeko lehen orduan hori nabari-nabari dago.</p>\n<h4>Non egin argazkia</h4>\n<p>Bilatu katedralen edo harresien bolumena landarediaren atzetik. Ez hartu dena garbi eta zuzen. Hobe da hostoek irudiari aurreko geruza ematea; horrela lekuaren intimitatea mantentzen da eta ez da ikuspegi hutsa bihurtzen.</p>\n<h4>Nola jarraitu</h4>\n<p>Patio Chicora igaroko gara orain. Oso gertu dago, baina espazioaren eskala aldatzen da: lorategi intimo batetik harrizko antzerki txiki batera pasatuko gara.</p>",
          "script_path": "../content/eu/dia2_goiza/parada05.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96055,-5.6669&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada05.mp4",
          "video_exists": true
        },
        {
          "id": 6,
          "time_rel": "00:50",
          "title": "Patio Chico",
          "short": "Patio Chico",
          "lat": 40.96114,
          "lon": -5.66702,
          "blurb": "Hiriaren harrizko teatro txikietako bat da, eskala egokia duena.",
          "photo_tip": "Behetik pixka bat gora, dorreen eta hormen geruzak pilatzeko.",
          "hidden_detail": "Goiz-goizetan nabarmenagoa da hemen bolumenen arteko elkarrizketa; jendeak huts egiten ez duelako, baizik eta isiltasunak irakurketa errazten duelako.",
          "image": "../public/images/generated/patio-chico.svg",
          "script_html": "<h3>06 · Patio Chico</h3>\n<h4>Sarrera</h4>\n<p>Patio Chico ez da askotan lehen zerrendetan agertzen, eta agian horregatik mantentzen du halako xarma berezia. Ez da Plaza Mayor bezain handia, ez katedralen barrualdea bezain ospetsua, baina hiria ulertzeko eskala bikaina eskaintzen du.</p>\n<h4>Zer begiratu</h4>\n<p>Begiratu hormen, dorreen eta maldaren arteko geruzei. Espazio hau ez da “plaza” handi bat; ia elkarrizketa arkitektoniko bat da. Hemen eraikinen bolumenak elkarren kontra ez, elkarren ondoan irakurtzen dira. Goizeko argi baxuak ertzak nabarmen uzten ditu, eta horrek harrizko gainazala oso plastiko bihurtzen du.</p>\n<h4>Historia</h4>\n<p>Patio Chico ingurua katedralen eta unibertsitate-hiriaren arteko lotura diskretuetako bat da. Hain zuzen, hori da bere indarra: ez du protagonista bakarra. Espazioak berak antolatzen du begirada, eta horregatik leku askotan baino hobeto ulertzen dira Salamanca zaharraren dentsitatea eta geruzak.</p>\n<h4>Bitxikeria</h4>\n<p>Turista asko bertatik igarotzen dira helmuga handiago baterantz, baina goizean, jendea iritsi aurretik, ikusten da espazioak berak zer nolako akustika eta isiltasun maila duen. Hiriaren irakurketa ez da ikusmen kontua bakarrik; soinuen dentsitatea ere bada.</p>\n<h4>Non egin argazkia</h4>\n<p>Jarri zertxobait beherago eta zuzendu kamera gorantz. Horrela, hormen eta dorreen gainjartzea hobeto ikusten da, eta lekuak duen “eszenatoki” sentsazioa indartzen da. Hobe plano bertikala horizontal zabalegia baino.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik hotelerako itzulera hasiko dugu. Ez dago zertan beste geldialdi handirik egin: paseoaren azken zatia digestio moduan hartzea da onena, ikusi duzuna barruratzeko.</p>",
          "script_path": "../content/eu/dia2_goiza/parada06.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.96114,-5.66702&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada06.mp4",
          "video_exists": true
        },
        {
          "id": 7,
          "time_rel": "01:00",
          "title": "Zenit Hall88-era itzulera",
          "short": "Itzulera",
          "lat": 40.9702112,
          "lon": -5.6766756,
          "blurb": "Ibilbidea biribiltzeko, berriz ere eguneroko Salamancara itzuli.",
          "photo_tip": "Ez da azken argazkirik behar; hobe buruan eramatea argiaren sekuentzia.",
          "hidden_detail": "Ibilaldi motz honek erakusten du hiria ez dela beti distantziaz neurtzen; erritmoz eta begiratzeko moduz ere bai.",
          "image": "../public/images/generated/hall88.svg",
          "script_html": "<h3>07 · Hall88-era itzulera</h3>\n<h4>Sarrera</h4>\n<p>Eta horrela ixten da zirkulua. Hasierako leku berera itzultzeak badu gauza eder bat: hiria ez da berdina iruditzen, nahiz eta kale berak izan. Orain baduzu barne-erritmo bat, baduzu argiaren sekuentzia bat, eta baduzu Tormesetik igo ondorengo eskala-aldaketa buruan.</p>\n<h4>Zer begiratu</h4>\n<p>Helmuga baino gehiago, saiatu ibilaldiaren arrastoa nabaritzen. Gorputzak badaki jadanik non estutu ziren kaleak, non zabaldu zen paisaia, non agertu zen harria epel, eta non sentitu zen hezetasuna. Horrelako paseo laburretan memoria fisikoa oso garrantzitsua da.</p>\n<h4>Historia</h4>\n<p>Hiri bat ezagutzea ez da datu multzo bat pilatzea. Batzuetan, ondo aukeratutako ordubete batek askoz gehiago ematen du egun osoko lasterketa turistiko batek baino. Goizeko lehen tarte honek hori egiten du: orientazio emozionala eta materiala ematen dizu.</p>\n<h4>Bitxikeria</h4>\n<p>Paseo on baten neurri ona da amaieran beste erritmo batean ibiltzen jarraitzen baduzu. Hau da, helmugara iritsita ere ez baduzu “bukatu” sentsazioa, baizik eta hiria hobeto irakurtzeko prest zaudela sentitzen baduzu. Hori da gida honen helburua.</p>\n<h4>Non egin argazkia</h4>\n<p>Ez dago hemen azken argazki derrigorrezkorik. Nahiago nuke azken irudia buruan uztea: zubiko isiltasuna, ibaiaren hezetasuna, Casa Lisen arintasuna eta Patio Chicoko harria.</p>\n<h4>Nola jarraitu</h4>\n<p>Hemendik aurrera, nahi baduzu, gosaria lasai hartu edo kongresuko eguna hasi dezakezu. Baina hiria dagoeneko ez duzu atzokoa bezala ikusiko.</p>",
          "script_path": "../content/eu/dia2_goiza/parada07.md",
          "maps_url": "https://www.google.com/maps/dir/?api=1&destination=40.9702112,-5.6766756&travelmode=walking",
          "video_url": "../public/media/dia2_goiza/parada07.mp4",
          "video_exists": true
        }
      ]
    }
  ]
};
